let globalData = [];
let filteredData = [];
let charts = {};

Chart.defaults.color = "#8b949e";
Chart.defaults.font.family = "'Outfit', sans-serif";
Chart.defaults.scale.grid.color = "rgba(255, 255, 255, 0.05)";

async function init() {
    try {
        const response = await fetch('data.json');
        globalData = await response.json();
        
        // Assign IDs to base data
        globalData.forEach((d, i) => {
            if(!d._id) {
                const str = `${d.region}-${d.client_name}-${d.campaign}-${d.amount}-${i}`;
                d._id = 'base-' + btoa(unescape(encodeURIComponent(str))).substring(0, 20);
            }
        });

        // Apply edits from local storage
        const edits = JSON.parse(localStorage.getItem('editedBillingItems') || '{}');
        globalData = globalData.map(d => edits[d._id] ? { ...d, ...edits[d._id] } : d);
        
        // Load custom items from local storage
        const localItems = JSON.parse(localStorage.getItem('customBillingItems') || '[]');
        localItems.forEach((d, i) => {
            if(!d._id) d._id = 'custom-' + Date.now() + '-' + i;
            if(edits[d._id]) Object.assign(d, edits[d._id]);
        });
        
        globalData = [...globalData, ...localItems];
        
        filteredData = [...globalData];
        
        populateFilters();
        addEventListeners();
        renderDashboard();
    } catch (error) {
        console.error("Error loading data:", error);
        document.getElementById('kpi-revenue').textContent = "Error";
    }
}

function processOptions(key) {
    const rawItems = globalData.map(d => d[key]);
    const unique = [...new Set(rawItems)].filter(Boolean).filter(k => k !== 'Unknown' && k !== 'nan');
    unique.sort();
    return unique;
}

function populateFilters() {
    const freg = document.getElementById('region-filter');
    const fclient = document.getElementById('client-filter');
    const fops = document.getElementById('ops-filter');
    const fsales = document.getElementById('sales-filter');

    // Clear existing options except "All"
    freg.innerHTML = '<option value="All">All Regions</option>';
    fclient.innerHTML = '<option value="All">All Clients</option>';
    fops.innerHTML = '<option value="All">All Ops</option>';
    fsales.innerHTML = '<option value="All">All Sales</option>';

    processOptions('region').forEach(opt => freg.add(new Option(opt, opt)));
    processOptions('client_name').forEach(opt => {
        const label = opt.length > 50 ? opt.substring(0, 50) + "..." : opt;
        fclient.add(new Option(label, opt));
    });
    processOptions('ops_name').forEach(opt => fops.add(new Option(opt, opt)));
    processOptions('sales_contact').forEach(opt => fsales.add(new Option(opt, opt)));
}

function addEventListeners() {
    ['region-filter', 'client-filter', 'ops-filter', 'sales-filter', 'time-filter', 'date-from', 'date-to', 'search-filter'].forEach(id => {
        const el = document.getElementById(id);
        if(!el) return;
        el.addEventListener('change', (e) => {
            if (id === 'time-filter') {
                document.getElementById('custom-date-group').style.display = e.target.value === 'Custom' ? 'flex' : 'none';
            }
            applyFilters();
        });
        
        if (id.startsWith('date-') || id === 'search-filter') {
            el.addEventListener('input', applyFilters);
        }
    });

    document.querySelectorAll('.sidebar-link').forEach(btn => {
        btn.addEventListener('click', (e) => {
            document.querySelectorAll('.sidebar-link').forEach(b => b.classList.remove('active'));
            document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));
            
            // Add active class to clicked button
            let targetBtn = e.target.closest('.sidebar-link');
            if (targetBtn) {
                targetBtn.classList.add('active');
                const targetId = targetBtn.getAttribute('data-tab');
                if(targetId) {
                    document.getElementById(targetId).classList.add('active');
                }
            }
        });
    });

    const toggleSidebarBtn = document.getElementById('toggle-sidebar');
    if(toggleSidebarBtn) {
        toggleSidebarBtn.addEventListener('click', () => {
            const sidebar = document.getElementById('sidebar');
            if(sidebar) {
                sidebar.classList.toggle('collapsed');
            }
        });
    }

    // Modal Events
    document.getElementById('btn-add-item').addEventListener('click', () => {
        document.getElementById('add-form').reset();
        document.getElementById('edit-id').value = "";
        document.getElementById('new-billing-type').closest('.filter-group').style.display = 'block';
        document.getElementById('add-modal').classList.add('active');
    });

    document.getElementById('btn-cancel').addEventListener('click', () => {
        document.getElementById('add-modal').classList.remove('active');
    });

    document.getElementById('add-form').addEventListener('submit', handleAddFormSubmit);
}

function loadFile(url, callback) {
    PizZipUtils.getBinaryContent(url, callback);
}

function handleGenerateClick(e) {
    const btn = e.target;
    const id = btn.getAttribute('data-id');
    const rowData = globalData.find(item => item._id === id);
    if (!rowData) return;

    // Show generating state
    const originalText = btn.innerHTML;
    btn.innerHTML = '⏳...';
    btn.disabled = true;

    try {
        // Decode base64 template
        var binary_string = window.atob("UEsDBBQAAAAIAACJ2Vzjjog4qAEAAGIIAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbLWWTW/iMBCG7/srolxyqIhpD9VqReihH8cWaVlpr8aegFV/yR5a+Pc7DhCtEF3TpblEimfe930ydpRM7jZGF28QonK2qa7rcVWAFU4qu2yqX/On0feqiMit5NpZaKotxOpu+m0y33qIBYltbMoVov/BWBQrMDzWzoOlSuuC4Ui3Yck8F698CexmPL5lwlkEiyNMHuV08gAtX2ssHje03IGU3i7L4n7Xl6KaUpmkT+vspCKAjkcS7r1WgiPV2ZuVR1yjPVNNyq4nrpSPV9TwQUKqfByw173QLIOSUMx4wGduqIuJdURnfhvNFIKZBefjdf1vtxO4rm2VAOnE2pCk7k2THwRU0LOfYiBdF8wo5eJsSEORIEf+c9nCBfh8+GGfkvrMxHcXJOtxL33c5Ea5AmKk18Louq8YrmyWg0ZlHUL8eo6DcxahpdA5X+j/mH6Oobc+A4JYw+Un/wRCMj4rf6CN6K2zECvgcpAh7Iyz+XZtFhBI8vUEvXUWIgIi9Q2wEQfnPAJu9RAnYeebjUf6UsLuevlZ6Gyyke+w+DnY3P8yP4Cw7hdh+gdQSwMEFAAAAAgAAInZXDnYfF7pAAAATQIAAAsAAABfcmVscy8ucmVsc62SzUoDMRCA7z5FyCWn7mwriEizvUihN5H6AEMyuxvc/JBMtX17Iyi6UEsPHjOZ+eabYdabo5/EG+XiYtBq2bRKUDDRujBo9bLfLu6VKIzB4hQDaXWiojbdzfqZJuRaU0aXiqiQULQcmdMDQDEjeSxNTBTqTx+zR67PPEBC84oDwapt7yD/ZshuxhQ7q2Xe2Vsp9qdE17Bj3ztDj9EcPAU+0wLoyBQs2UXKtT6zo1LxmAdiLW00TzVcAFNqKlrCeaPV9UZ/TwueGC0ygomZLvt8ZlwSWv7niuYZPzbvMVuwX+FvG5hdQfcBUEsDBBQAAAAIAACJ2VzvKBONygEAANkDAAAQAAAAZG9jUHJvcHMvYXBwLnhtbJ1TwW7bMAy9D9g/GLo3iou12AJFRZFi6GFbA8Rtz6pM28JkSZDYoNnXj7Ib12l3mk+Pj9TTE0mLq5feFnuIyXi3ZuViyQpw2tfGtWt2X30/+8qKhMrVynoHa3aAxK7k509iG32AiAZSQRIurVmHGFacJ91Br9KC0o4yjY+9Qgpjy33TGA03Xj/34JCfL5eXHF4QXA31WZgE2ai42uP/itZeZ3/poToE0pOigj5YhSB/5ZN2UXvsBZ9YUXlUtjI9yPKi/EaZKRZb1UKSpeAjEI8+1kkuBR+B2HQqKo3UQnkh+CwS1yFYoxVSa+VPo6NPvsHibvBb5NOCz0sEvWEH+jkaPGT9eSh+GDe6GAG5iqqNKnSv1qZI7LSysKHXy0bZBIK/EeIWVJ7sVpnsb4+rPWj0sUjmD832nBVPKkHu2ZrtVTTKIRvLxmDANiSMsjJoSXuKBzgvm2PzJZscwWkhnzwQPnU33JDuGnob/sNsOTc7eGAzex+cHe94p7rxfVCO+ssnRA3+ne5D5W/yZrz28JSczfzRYLcLSsO76c94sSMWahrnNJGJELfkP9qsTmddC/Wx5mMi79PD+KfK8nKxpG9YoCNHazD9QvIvUEsDBBQAAAAIAACJ2VyWuzOMbQEAAL8CAAARAAAAZG9jUHJvcHMvY29yZS54bWx9ksluwjAURff9iohNVsYDQ8EKQSoVmxYJqUGtuqks+wFWEyeyXYa/bxJIgLbqLs497+j5JtH0kKXBDqzTuZmEtEvCAIzMlTabSbhK5mgUBs4Lo0SaG5iER3DhNL6LZMFlbmFp8wKs1+CCUmQcl8Wks/W+4Bg7uYVMuG5JmDJc5zYTvjzaDS6E/BQbwIyQIc7ACyW8wJUQFa2xc1Yq2SqLL5vWAiUxpJCB8Q7TLsUX1oPN3J8DdXJFZtofC/gTbcKWPjjdgvv9vrvv1Wi5P8Vvi+eX+qpIm6oqCZ04UpJ77VPA9aO0IHxu4+UMUTb+YBG+ell1mQrnF2Xraw3q4RivlDgGT9oKE+HfaTVgYaerbxbfkxppz41tabXxoGJG2ACREWIsIQPep5yQ91baQNG5t9NOoILyvvzUTpO89maPybxT+ugYUYJYPyEj3hudfD/mL8LsvPa/RjZEZIjYIKGU9+itsRHE9dK3/1z8DVBLAwQUAAAACAAAidlcSpFI1MIEAADmFAAAEQAAAHdvcmQvZG9jdW1lbnQueG1s3Vhbc+I2FH7vr/D4haesbMzFeBZ2CCRbZtptJkm3jx0hC3BjSx5ZQNid/vceyfIla0IN2T5084CsI51P37nayvsPz0ls7ajIIs7GHfed07EoIzyM2Hrc+f3x9srvWJnELMQxZ3TcOdCs82Hy0/t9EHKyTSiTFiCwLNinZGxvpEwDhDKyoQnO3iURETzjK/mO8ATx1SoiFO25CFHXcR39lApOaJbBcTPMdjizDRx5bocWCrwHZQXYQ2SDhaTPFYZ7NkgfjZDfBOpeAAQWdt0mlHc21AApVg2g3kVAwKqB1L8M6Yhxg8uQuk2k4WVIXhPJvwypkU5JM8F5ShksrrhIsISpWKMEi6dtegXAKZbRMoojeQBMZ1DA4Ig9XcAItEqExAvPRhiihIc09sIChY/trWCB0b8q9RX1INc3Q6lB43bHwnEjRJ9lnMlCV7TxXa4+N41Few0JGoMfOcs2UVp2h+RSNFjcFCC7Uw7YJbFddja3Zam91trmeRgqwDb0TeySOGd+GtF1WkRTQZQabSi8PLNgkkAGVwdf5Jqac92WzacA6DYABoS2fFkUGL7BQKSqboUTtSyrAmdQ4kRhDecyMjWAcHsWRNcreKhBqdewslCGm/PgihghpYsl3uBs8xJx1bIRFIi9GmKeYDEnT3VMep7T+iXgIanFMF2/rVA/Cr5NK7TobWiLqmXv2XkGOoNvsyLN3kbmYYNT6OQJCRZrxgVexsAIyteCCrR0BKy8BNRg5VVlFfljFWG3dHZaqiXaE/gIXPLwoMYUFnpBigVeQA0N3ak3u3XmtpbCK1RqqfkDaQDfm+H92HYcv9sf3QxK0Z04IpzTFd7GsrlyVxNpFndCDSIflkj/zjI9xpitQW2HIXUpu1p8skGMzGZkdNXYNMfr9a4dfzb8UcyZj2ajkTf9Ucy5nt52+971/84cmB5lchnqPtA3sSBLMYHKTgXNqNhRe2KpLTLf+JoPh7PrvudN+y186PbcW++mtQ9fbq/7UJuUNn9rvv2LFOYS+IKjwthbeK/hqOxLsb/nf+ObyeLT598Ws5vjzqhONrvnWNLA+gpvP/p3S5XrKI5paD3y4LjCMcp1gl9JHIGVfzKcnDxTLmMzGM1l/CAPMS1Mf1St/aOAL5Ji+x+wJA8pZAXeSq5iAV9/Trn8C+dPIFtFIpMzHm8TNrZdu5Dc872ZxrhadwqBXtYzxn++xiwsZ5/zmVbVxJze1DFRqZNXVNXjGkaAz9n1Xc8QPCpGLzRlDkXyXwNMKqvDZ2w39c3Gf43LnGZERKm6gxyJCqoO/m+OnyZ8y+TrJ6PS/u/jBTmZYbi6RmsG+U/M44ukBI4CmZwXEGPYt1Tjq5n7/XwEVYK1P04cYxyCyko51VdEtN7I022lHoxHLnEM9r5OApoQJfJOnNkyH0BJSYfz4cCf6lfAhuKQinu6ooIyQitX5c3VtkSg7itiEfp5paw4l+0URqb5rh++5E533ZGjucBNwR34nq+eCQ9Bu9z7K1ZGSQ6XV7fv6SLX3oP3RE/rLrmUHG7mruPn7YGuYHHk6ElujWkOOVOItZ6tt1LmS/okwuMMpOY9NuwacciJqneFGzF6F0kCXL1BkSu51/Vj/k2Kqv9QTv4BUEsDBBQAAAAIAACJ2VxFhwEPRAEAAE0GAAAcAAAAd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVsc62VzU6EMBSF9z4FYcNKCqOOoxmYjTGZrWLittDLT6QtaS8qb28zKDDjpJlFl/eQnvPl9KZsd9+89T5B6UaKJIjDKPBAFJI1okqCt+z5ehN4GqlgtJUCkmAAHezSq+0LtBTNGV03nfaMidCJXyN2j4ToogZOdSg7EOZLKRWnaEZVkY4WH7QCsoqiNVFLDz898vT2LPHVnm18Lxs6uMRblmVTwJMseg4Cz0SQGigDZRypqgCN52GOQ2Pkk/P5Ny7zNQ4t6Dl/nG3x9y7jQTAhcQnwp9gQVi4RRM9zUGa5ZoZJskHELiGKXqPk7yZtggjDWSUNArcuxdolTSklnlzLJFkrcdoJmrMwExzGUbQ2ceeS4QvyV0A0q7DoYiFa24jc3onAjOYtLO/kV7JR3Dp9Lf51oS8o4sH1bi4fzHGeNoIc/QXSH1BLAwQUAAAACAAAidlc/RIfDx0FAABRFAAAEAAAAHdvcmQvaGVhZGVyMS54bWzlmN1u2zYUx+/3FIQGLFcJJevDtla3cJM6C9AVQdo9AE3RlhaJFEjajvf0O6Q+LEdtKjvL1QpUpA7J3znkn4ei8+7DU5GjLZMqE3x24V25F4hxKpKMr2cXf31bXE4ukNKEJyQXnM0u9kxdfHj/y7tdnCYSwWCu4l1JZ06qdRljrGjKCqKuioxKocRKX1FRYLFaZZThnZAJHrmea2ulFJQpBZ6uCd8S5dQ4+jSMlkiyg8EGGGCaEqnZ04HhnQwJ8RRP+qDRGSCY4cjro/yTURE2UfVAwVkgiKpHCs8jfWdy0XmkUZ80Po/k90mT80i97VT0N7goGYfGlZAF0fAq17gg8nFTXgK4JDpbZnmm98B0owZDMv54RkQwqiUUfnIyYYwLkbDcTxqKmDkbyeN6/GU73oQeV+Proh3B8mFuwd0UsyedK92MlUPWrhp+I+imYFzbVcOS5bCOgqs0K9vToTiXBo1pA9m+tADbInfak80bmGo/OtpuKhkOwCHh19oVeRX5y0TPHaCmQbQjhoRw7LOJpIAdfHB81tJ0FtcbePg0gFEPEFE28GPRMCY1A9NDdhtONjCtGk7UcrKkwzkvmA4g2ZyEGPlNHKYwwzsslegkPQ3XaITNWKJJSlR6TFwNPAgaYtAhVhssF/Sxy2SnLVrYAvdFR8Ny/bpEvZViUx5o2etod4cje8dPm6AbPd8VpXpdMF9TUsJJXtD4bs2FJMscIoL0RZCByCqAqhQwBaqyCjX7BzWyI7s7kTkSnfdw/yvBEMQlkeQOcmc8vwnH4/Enx1rh06mttf4H1hiumMnDzHHdxcS7th0r0700xsnIi8KD8YatyCbX/e731uTDJBdVFPfSFl/1PodpxFsC+/MPRhImHWxaNFmqumyaac6INMBSwMpO/cg1XfGhb8ZhKeKcrSCASy8YWefZOjWvQVRx/6YtDj4xjTdZhSMXgmsFHYiiGWylb1nBFPrCduhBFIQbXjrn6vstVPXNFs7FvRRiZevqn8b9KHBqy7U6tuE6Hlwvkyn7ykXzMPKuPX+Act409Ofjwcodd/8/K/ffqRXOvU9esPCO1fLDj+Mo8NwjtZ4J8zO1PgbjYBIdqVWb3litH+tjW95cnucLD68dj4ekw62tvp9BtYQ55BlnKMmU/gZr5tjax7b2ua092Jo5PmPCaSqklXM8iabuNKgbWJJZPUNv7s2jcO5YFyAybFRkfhd7U98Px6GD6H7mBNNw6od2faDTasWo/lR1za0vbZ/SPpfmWfVMBL2XyFx4YCt4o2DkjkF2Tgr4KtxnVG8kQ92WhCkKkDlaS8Y4opmkZgtkOkXLnNBHlDMNaaR++9Vzf7eP+d3lmnEmiWYJoqCYiakge7RkKONUSAmhXtXh0C/bW0nKNKMLCTGYFSbxumP5DPcF1fz+OeP6XF1aubhOCV+zuSrBOcy9kv5l/6/12kHdwG0KbWT/XvFzVFmJAjSoxWUbFtReTeNbkNzM2bzAUtQ7w/ef7whjecud0PivoiFmcpXwfeEOJinFLoVDSDV6HlNwb4bLPCsXWZ4bD6aOZMyKJYMZQzpaBImVlkzT1FRX0PUBvBp0pwEfo8ybgqMDLXd/wg/tmUM2Wljtn1ayMCVc0NCTzcN9nYfEZHWd0pPAD4MqpUN3AkntVP6a0aVU+paJApkKRAoBWTrZflZ1aE0XY+bChGV95PzIgCsLbgKuq/DftnV2ave9SpPqnLOnYHv8YXtUVh8qbP8i+P5fUEsDBBQAAAAIAACJ2VyfaapxswAAACABAAAbAAAAd29yZC9fcmVscy9oZWFkZXIxLnhtbC5yZWxzjc+xCsIwEAbg3acIWTLZtA4i0tRFBFfRBziSaxpsLiGJom9vwEXBwfHu+L+f63cPP7M7puwCKdE1rWBIOhhHVonL+bDcCJYLkIE5ECrxxCx2w6I/4QylZvLkYmYVoaz4VErcSpn1hB5yEyJSvYwheSh1TFZG0FewKFdtu5bp0+DDl8mORvF0NB1n52fEf+wwjk7jPuibRyo/KqTztbuCkCwWxT0aB+9l10SyXA69/HpseAFQSwMEFAAAAAgAAInZXGEhqKC/HQAAuh0AABUAAAB3b3JkL21lZGlhL2ltYWdlMS5wbmcBuh1F4olQTkcNChoKAAAADUlIRFIAAAGuAAAAjAgGAAAAJOZNEwAAAAlwSFlzAAALEgAACxIB0t1+/AAAHWxJREFUeJztnbtuG8uWhruNE0wwgHWyycyTTWbOE5g7J2D5CUw/waETppbTTsz9BKaeYNNAB5Nt6gk2lU12pGyykYAJJhiAg9L8pV1udbOre61qVjX/DyBk60J29aX+WqvWJT8cDhkh50BeFtMsyy7wmnoO+SHLsj3+fXeYr+54sxByWihcZHTkZTGDME3w1bxeK47z3ohYlmU7fN0f5qu9x98RQhSgcJGkycvCWE8z5/W2Mh5rMVlLaZFl2TrLsq39hcN8dZOXxTsI0QK/f+G8xwSvDJ9TZ7E94u/Me2wpZISEg8JFkiMvCyMil3i9c47/AV+NsCyzLNsc5qtH+8O8LL5kWXZlfm6+D7GyImTFb+e8nytYWeVnbe7GR4ijFbKHI79LCOkAhYskASyrBV6uVeWKw31eFv9lBOwwX/3N/kJeFm8gMhvn71yLaudYZhN8hmF9mK8+V89PXhbfnd+ZmM/F962ITiov89k3ENJt9f0IId2gcJGowX6VsZ7eO8e5hQj8cI89L4uPEKcNxMhaUZPKGO/wnnsrOs57fMPPMvydDeaYOd+7rAhfE25gh/37RxzfmoEehPSDwkWiJC+LBdx6b3B8d44ATWoE5w0EYVYZz85x8V3h6+IwX11X/v41LKOtpyhpYKywq8N8tQv/UYSMBwoXiQa4A5d4vYbFskEwxQz/Ni7BD9mfYmPdh+5+09a+7B5XXha/wVJ6qARa2JdveHwIKGCEdIDCRaIgL4srR7DuIFYbR3j+cIIoMkewqhj337+534M1Zt1ydxCvUwpVExQwQjygcJGTkpfFJUTqDQRlWePGe+smATsW0wP+9sLZl/rJDQjRWsPaSoUbjIN7YITUQOEiJwEh7ZtKOPuFG75ucdx8ljtYJk8ClZfF77DETDThX7M/AzUWNXteKfErxslQekIcKFxkcOAW/FL53N1hvvrF/QbE58qxsHZwH1YtKmuZbGGZLQcMsAjNPaxQhtETAv7CE0GGArUCN8jDuoNFZPdznt1iyIfaVMLYjWB9qjnUK+ffl4m5BH0wwvxbXhY/4D6k9UXOnlfnfgLIMMDK+gOidYUEYXcP585YT3D77Wpyr14ELMDaGptQNWHy2PbIayPkrKHFRYKCEPct9rLuYDXc4DNdcZpWagTaoAsbOfjsKoNgXTVEFY4ZM+7f87L4epivrs5s7IQ8Q+EiwYBrcIsJdwvRcoMv3JB0aznt8Xu3eVn8w34PtQVfQ7CWZ37VvuDc0nVIzhIGZ5AgoPLFGnlZtftTlZp/D3Ah/pq9DLq4cnK7xhJ0ocEtxIuV6MlZQYuLqFMTNfhTPhIsp02dleX8mrt3tajZ8yL/v1+4M/teFC9yTjA4g6iSl8WmJtT92Z3lJBNbYTLFZv+tIlpZJf+KotWMWQT8AQuXkLOAwkXUgGh9rAhTZqteIC/LjRhcNrQNOadoQS2+U7zIuUDhIipURGvmWlnZn00cN5U9qhfuLYgb3V79oHiRs4DBGURMXhZb5Bk9B2E4rfAzCNGLoraH+Sp3/18J1iD9+XSYrzY8f2SsMDiDiICl9R4tRNzIwWnNvze2zqD7mQjW2EVasT1FjOWVUbzIWKGrkPSm4h6sWkrVsPVlQ0i8Lf9E0dLlOyrvEzI6KFykFwh5f97TchOLYUH9FM5u87PcaEFnP4u5WWHYIFGZkFFBV+EIwOQ0gwBMKtXUM7jx1AIeEABgQ94va1qRuG6/F23yHejKCstr5HlNWGGDjAkGZyQMBOQKJZXaUGmPAZHcYVLMYG3dOD93AyxeiJbTO4sMxy2uE8WLjAJaXAlSKVzri22P0TvizPnc1863L5yfHxWt6u+PAEmh29mAAv4W5bIYsUlGAYUrTaqdg7uwzsti17Mt/KbGujMW2I+8LP7uTIxXdaIFYRvLnos5h1/7/vEJ9p4+4rrTPUuSh8EZiYFIsfeCo64GTniRl8USn7urWBoXeVm8x4o+QyX3FxP6CHO0pG63U1ieawZrkDFA4UoPjZYenSZNTHbfMFlXxeeyEmTxoq7gSBOLpcEup9jne82AGDIGKFwJgT2mvi5Cl66Tpp3szL7VfaUb8aQihD+JIkLex7i30sfV+gTSBU7FW6QyEJIsFK600Fqle1sLmOTeIqT+R8OvPTS01v844hV+b+GKYJ/vC12GJGUoXGmhNdl47c+Y/B/ka/3kInTD38GiKlyoiDFmt5REuGJo07L2+B1CooTCdZ74WlxWeK4qlTHcyMJ11RLDz19YYGMCLtO+xCBc71hJnqQKhes8aRUuRC++Q5Tgr5UfW0HbN+Qyjb2MkzQwIxY33Rr7poQkBYXr/Lj1zOGyrqSfohiRr2X32haOJeZO5mOfDFMMha/jtVKUKiGDQuFKC8m+iqV1bwMupDfor+WWc3rtWFhXlXb751ROSOoGjank1RfsZRKSDBSutDDllqoFbbtw41k5wYpT1aW1hrVQm2R8RvQW6ROHwjfB8HiSFBSuhECR1L6unRufihmOtWWY2kAMdDS2m/l1x3BOUWqSPa4Yw9A/0uoiKUHhSgxYTB9Q7d0H83ufD/OVb3Xw6ur7svL9TTUcPi+LL2fWCDL1UPg6aHWRZGBbk4TJy8KtMD6FG+8OrwcUgu2SbGwsqu+Vb9vIQdsOZeN2Mka+llqvrxQ4zFd538OEyMcqEn9l6xOSAqwOnzCH+WqnnC+1dL5a19+0kkhcDSw4t0RWqUjH7JJb0vIiKUBXIXkC1ttbJ2/LdYe54dsTG2BQCY0/F6QWSczCxYRkkgQULmKxk5a1oKqdkt3/zyqh8eeE1MKNeS/wDRLPCYkaChexVedNQdwHpwGk6x68O8xXH5z/zyBa51h1YSzJx03Q6iLRQ+EimRM5+GxVIbnYTtLWsrL7O4szrrjQe48LKQWx855loEjsBA3OwL7JxOnZ5Osm2WPSvMOeS3JRa3j4Zxiz7z6QiQI8hfvNrrKfrSzkb13A2rJW2M6JXtTERkJaN9ze07K5cI5nGujYqkhC4duO7Q5j3zvn5Bh2vDPlsS9YPZ7EjJpwORP1JR6it4K3+2llmpdFhgTaLfpCaZQ+ct//Cu07fLk/zFe1m+wQ62XP9vqN+yd4X4moLerOGxJP30Gg3Pwsa1G5E9hOydLa41rualqkdKWuMr29D9X3a4RV4esWblvnvu5aFcWeu6cqJkhNWOAlEbHOwoVUit5uRpNn2PdvK8exFuwjmkXy0fsbfcxSEvXWxTD2NVPyoGzEwoVBL3pO1F14h9e3vCxukE+k1e+p641uNrEnrhA4N7TEHXRMkGeS9z4i9nbCqP58AavHPceSwIQ7nJ+tcPI/Ct7bWIjXCCBZ4qVhjUgXTHax84Bzse4hVo3AvfvZvNDEc91z3KZL8kXHnK5Lwf2peT9MBcfhc31Fz+EJ8HlmJefsFGx773GZFVZeFuZC/zaAaFUxJ/l7XhZ7pU6ufR7u59V8XhZmYvxD4eIfe3AkYdTHJgY7jplT3ukjzknVCuhzrs2DY6p2/M2E2YcUrSrm2FFTcaIUAakhXEZMzKLnq6ZoVYF7d1ITHepLV2tVsjDQ9KCEWjhaUtv/8xlTalVv9p2Fy7isIFjfnZp2p8K4Rv6AcEjoc7PPcD6MRfJNafzH9vIkwnXs5nUXHZeVr1WXSBdX0APck78ouANFOAI2E0YFSvdal4f56nNIwXLBuD/07ETdVbgkgqGyh60QVOJzHKnlLY5SjL2Fy9wU8B//HoFgVfkGAemM4GZ/j8/8qDWIFteMZFVU+0Bi38xlCffaJfz9t87vvukgXFtYFdcevzsYEFCJeIlC4SttYIYc96ce4jXkBK1VZkpqOfgGBKWEjxgnZXGZbQ8v4cLkblw+fw9/WL352NPyklw0NdEyDR5bfi5ph9H0QFYnp4ljZVUnOt9za/p0fRjKqugKxKOveGmW1xoUiFeX43/t64avWQB1Reu8iqqSoIRaG5Kgs8Hx3KeMsdVOE0/zZKtwOaKVwgX71mPPK5YVVOMNFnBisO/rfra1qp4nAVhhPtbWIoU+XRCvPnteqReg7Rr153vfSZ8hrfMqEa7WhVaC+W2tLnqFuWVonu6Vo8KVmGhZuoaqxmImH1vthXpg7L5E3X7Gwml6eOlxDMvYXIPHQD3GTiv9U7n6tEBgTBeXoe+zIXqGFPM01d3piu9/Csbo+nx6ZtssrtREy/Cu4yoilqKnofa3al0gjmVqc6mqm7gXlWrxx9hACFKjyyJHNXfwhHQZs+9zFCritSuhIxtTa7Y5RjF+olG4EIiRmmhZuux1xXIzhooobHKB2BvWPrDuhGa/t0RS67Gbe59q+afDfPWjgyCNQrhgNfpaOL5BWKEiXrsSOhQ+JeG69VykJDmm2gRkWCwhAjFuYFm4D84UJ09TJN93SKCMZcURKoeraZKaVH6+wU1hhWiHFWybO22hHYiBCMZJZcVv75u98udtPYU3aNkx1DGcVK71DhVNtHPfdr73vZkLPIIWQrvoWhkoFD7z2TcScqEwF5rn49Jz/nsYYEwThUj0W+SDPo2pqXKGZkmTaySyHk2ExI1nqxxoRLnMPJMvo4ioaSljJZkY2ipm7PH5jyit9eQ6RK7epMX9stba94FYXfnsp+VlsUX0osZn+wqXemAGxGrZljNlEu1xrrX2ELuU7vJZNIWIeO1K8FD40HVEnZgCCY+Y4L0s2bYSVwpjmiqM6SfRyuqECzXHNKyfm6b6eHXgoK6QG7VVOIZpm3AFjKh5xMXyLZbahmRiaPrsC/fncAlmzk121bKR/6BRjQIBIOuOEW9PdQjNvaowmfuutNVC4THmTYck36cu1Hg2LxUszi5WzlHhGksofGiLug2lQDgrWlEUJceYNsL5674qWlmDxaWxqrg+zFe9Cm4aocMDuhMO2OeB0o6oucf523as89aIQkmrppv46QFx3FDPwRr4/jWKDzdNCOI6exDLrWDSMZP5A/aqegFL887jGLSup2TM1ovwi+QYzDWHde1D2/0XS1SaNIfrZKkOIxYtjTHVujx/Cs6AYEh9kb1Fy4KTP0QFZs39LbPyn5rCv8oPgXqOjLMf8D/Ot6c1+0fHxiEqcAzX4E5hpaxxn7RaxBpuScfSkox5hlqSUv7b8+/b7j/1iNeeSI7jZCXJKFqNHB1TNapQ2v30RipaDtLK7z4RRloRNU9iHWjVJnLFNEwM9iH/J6e54dS1ziAsTZOBRoX3rdJqfZKXRegiz1qRbxulxZKGV+R/PX+v7RkJmvTbAcm9dMrEcorWS1rH9CxcTl8mCWptv7E3FrqSuIZw/VAU6zokD6TPxGAnwWnFrXhMMKXW1hdla1e6z9L20IuFCwsErf5gE2dPMjRtHpgQEa99OHmR365gP196HZfnJlpZxeKSPlTX2g0eB7ihpJPno6ZYNxAi1NgVwxkm1QtP4RLtKTk9sjQJHVGmcV9rR6TFUqonRMRrJxRC4QfP0VMq0P1JsSehiKFdnprCFSJUNLRwSUPh1wNs6oZI7qxONm7LfEvTxNi3v5NFq6mjS8zt+m1AhrbQxBIUESLitSvShcugwjU20QIa1uOlr/X4FFUItZSY2j8CWFtZyGrcSqHwQwSQSIJl2q7Jf2ZZ9i/O/42ofHUSgOuQXpMQFuoU7se+tN0L0gVUiDHPbMv+0JjI1roJJWDEa1eSCYUfo2hhTNJ95k9dAnVsOLx0EpeuwmvBQEKJl3TF+iO0tTXAxPAfWZb9uzOxLlHq69jn9r4esDxClZgJmRwqvc5ae1unoulZGUNV+MFC4UcsWoOPyboKpRNkin2KpGMOItYVhpgY3An/AiLWdG6k5YeSnMAlHZwDi/WpCRHx2ofoQ+EpWo30GpMVLskNeBvITRgaqSgMIVyho+XqWl0cK0Ekdamk1vsnU7AKQo1Zelz/rHAMoSNefZEsDIJbW8iPlU7w1xStP9GwuKIIxeyBZMz3A7kXROLa8Rjt6ndy5Nyco3BJxxyqiLP0uJrqlHYhlnlDEhQQuniyEa3vwrcRF3XQJAbr8RUCMySRQakKVyz5J8cYygUygcuwzXKW7m+liNSbEF2/I6dBqJSTtzNB/qmEYN6ikYrWWkG0vkqtx1cKD1aqwiWJ1htqzEO7QNoCHCRWZqr7PLEKl+Qe7HpMTZ8VMuLVlyiFa6SitVBod3WtUWVfQ7iS29+KKIy3jVDiagXIDYV/QKX1RnES1utLstOq5FojrSAUgy0i6lzOET1D0c1fIxataMb0SmEf5RwDM4bY0A35QNpJ41/t5OqIUpMJLx1zLAmzXYnSypREOiodVyzPUFTzl9IEH7qMXCdiFOJXERXJHJJYwniPMVQZm6rZ3jShxBqkEJQIBKIO6WSrESQTPOJ1gONQaYJqQVED6QR/O0AZOW9itR7/kkiQgjYprP5DumJccVpU/p9i5F8opFZBKOGSLpy6HFeQPCfFqNwoqsLDQyJNkXnR6feUxOzyrLY1ORdS6N0TLBS+pnyPz2dF8TANTKwLM8m+22slQY3F0pFEq6p4Tpz29JJozTGK1m0ol+e5ClfUCYtAMjGEENdUrWsJsYq1ZGWvFVEoIZbu4OLjGKloTRXqsN6G9N5IkxCDuNyQm9FbXDz2oFIIhQ/tArlpKKycmqtQsmpuu89iFOu9sOxW1+sbs6V90n22EYtW9GOSCleopNK1oNrw47FJP3C0niahqwHcQbj2qK7+XtJny/PztDGdmD/0fc+8LL63bIRLjznEmKVlf7pO9k0LA2nTWQ2kwtX7+ihN8PcUrX6IXYUKmet17ycpkd+2Ao++6dxA1QDunK/mnG0C5x3FOIm3Ff2NTbgeJGPG/lbXyT7KdBdU/BG10ugbCo/nUzrBP6L/FEWrBxp7XNquJWlWdZv/P5Yw3mMMIVxW4Kc45xct5y621jd3wk7Mbz0WMaJrLQylr8M0LpWkoHSuzh8oT1MjNULaRbtXgAgEc6sgWl6dfocgRZenhnCpRY1gJSOtgxW0avtAF2aIqgT2dyaO0AXLtUKCs+YkKL3vWv9eKBIWrfvxTmHDvKtwhYqgfS3xKkA8pMLV+Tkeuj39ECiJ1uDW4yuFkNB3St2EM4WH/Nrj5MUWrVdH8Krw+B27yT/1cEFpuIS1mj2uFayZNuHSSjLX6pJ9KRFSuAm7ClfIyVXyHF4JJ9qs6/UdqWhdKInWbOgKSq+UVsFrnITeoFS+NNjDx/8fRcJiC0PlyNiHd4bJ4Nj5EwsXaiFK96VMQMZnyRvkZfHR4z5QudYQWOmYF8I6kVnPJp7HJnfp8fRaxCgVes26XF+KViMnG9MrpVWVuaC7Pua/OYF5WWwVXIQ3nqWYou3d4zCUuLrC1ep+yctCHEl2mK8+CSbytSSK0MHHzah2rQVjNovKKQRfSh+hOPY8SYX9DRar3uRlsVRIirV4XV8l0cpgMccmWskK8St8sCQvxGJOwj4viysfAYNg2R5Qougg0Ppgxty7p8JQ1QDcAI0HD1eUiksYE/msw7Fu8ZCILK3sT/H1GYfqtcaYFx0iPpeH+epvCpaWGfP7HhbzbYvLWeP8fDSL1rbn0mxF5GVh7pVvCp9paT1+RdH6NFB901bGYj3aPK6dgsWTwez8Yl55WdxiVVO9QWyHXc0cMF9rK3rhUhBX75Ww8UvnZXGPhGwzmbet7I276avw+OxnGxfaL9h7mTaIyQ4Jt5rFnH33nNSvNSyna0Q0Tmvux71CgnEdffbZ2p6nvdKcYUT1fV4WNzWfOcVLPU3Dc09mrTBPmXt3ARdnaMzis9ElrCjED9geGmBIT8/DC0+QFS6NrpZV3gZMUK7iG2GUQh8uqXB1PcYt9gyWEK7dEYvEJCq/0wzzhijdDBH4kpfF3zvcA8GuNawo1crkTWA/r8891RYopW1BvBswqbl1YaDUnj7DYn6ocTU+Q4qilWEhETLns5WncHiYfENFzGnzuYPJGjxaT4GhrULXXeiDNAz5JMDK8d7nUbbyTjXm1z2trcc2DwaeuVTP0dFnJC+LywAL+SE4Nj8tBzQkNKm9D908rhQnJNNwrcuDmUIovEi4uoalHuarrZ2APIMvLjWCNIYEE/imw8Iliv0IBbY9F2u+aSnSaMlT0bbQHWO37lE1cn0WLqygVPYvBqJPw7Wx9+Hq636yE9XEc9LeQAyiB8e563hek2/hkpfFN8FCzVe4tHLUhqbt+gbrXB2YY4vWUYnxT5UzDvPVlccGfQz0LS9y8t49Hpwiz8xOQL439ySF1XZP0cpSb+GCfa2+HpR7WOGtwLr/Ve/IB6PtWR6jcI1qTHUln5aRi5epjjHtKlpDRusJkbjheomrkxIx6zBpX6K6epSgYHAf0cr6XmsjGKe2RBGAIllUdK1eczVUoIkibdd3jK7CkwZT9KVp6+OFcBlBQNfK2FZSZh/mg6Cj5tDRep2RVh8Riuu6xwNrwnz/CFxVvjOwOPaCCajztcY5WCMRf3DxMp+JhYTUfdfp77GAXJwgUOPXvgtsj2CuJNzgVZoW89odPAakcUHUWGQXsfO/RLKaMjfpxNeF0UAKfbhOGa5vV+ldxW+KxHONMjwiTNBIXha/dwzEqKPPtbYV9qcQr8EiuJBgvFcoPHzTp+YchGA20FxxjwXssmdt06Oh8Ar9+k7FseCxVIWrcS46Wh3ehMQat5zJ/D5BuPw9gkX+am5ShVB0aSj8EMJ1sgRpnN9rJBl3fZ8LJCT+4xTuMnzm7y05aN50TQBGlKUrGlbMv4Q8F45Qb5Ump97WmiNeoQK8HvHeU7uAdSNiO9B2b48q+g6kKsaNWx9eHZAP89UGkWQTTGyXgZLqbm1TwwDlRC4E4jtUqadBQ+FrMFbDb1i99zmW56AN1J80r512JQi45WZ4XSpPNn3uu6b8MPP9pT0XGh2mYcktMG7NlbR3UEYTWPxcIXl3gZfUjfwD565p327XsWRc2/XV7i84FGcTCm/ID4dD73eFWW1L10wqD1KdsN06B/PglIS6i6WW17mDmnD/0OyzZq+xs4Jyr/WLkk5OGSjLzPlavc9Swt7zO+ecvDgHEGY7RjveGc5JqEno0xFx6I0zR0ydazqpCNq9ey7w7z3nBNKESLjI+EBvte8JiwPpjrG2eL1JMmh0QCYjAqtc7SKvJG60GnwSMggULlLHEJWsSRzch3AREhISChd5AYI8UqigQuRwkUKSg8JFmlgmXP2b+OHbx46QqKBwkVoQ2pxqEVXiB60tkiQULtIIii6nVoeO+PF1oKR6QtShcJE2uCofH7dYlBCSJBQucpQE+7SRdrgYIUlD4SKt0GU4Kr4GKKdGyKBQuIgvp2hdQXShi5CMAgoX8QKr9L5ddcnpeURhXkKSh8JFvEGFBSYmp8klowjJWKBwkU6gAzX3u9LiMxONyZigcJE+zFiINxmuD/MVE8nJqGBbE9IL9Fkyq/hBux2TTtyigzkho4IWF+mF06qdkYZxcptwN19CjkLhIr2BeDGZNT6eRAv1JgkZHRQuIuIwX21N23eexWigaJHRQ+EiYhAmT/E6PRQtchYwOIOokZeF2VPZMmDjJFC0yNlAi4uogVwhBmwMzw1Fi5wTtLiIOnlZTGB5veXZDc41ksIJORtocRF1UFrIWF4/eHaD8pmiRc4RWlwkKHlZmGrkX3iWVXlE7UGWcSJnCYWLBIdBG6qY/awFC+aSc4bCRQYhL4sLiNc7nvHefGU/LUIoXGRg8rIwPb2uaH114hZWFjsXk7Mno3CRU4CoQ1Ox/D0vwFHMXtaaVhYhP0PhIicDe1+m6sYbXoUXmIjMJfeyCHkJhYucHEQeLuk+fOIWgsWIQUIaoHCRKEDwxvKMBcw05rxC3UdCyBEoXCQqzlDAbrGPRcEixBMKF4kSCNglIhDHuAf2A4JFlyAhHaFwkehBEMcCQpayFXaPYJQNgy4I6Q+FiyRFXhZWwFIJpb9H4vWGeViE6EDhIsmSl8UlivleRuZONGWZjAtwS7EiRB8KFxkFSGo2IjbFa6jSUiZJeA+h2nHPipDwULjIaIGYWUG7gKBl+Nplr8y4+8ye1ANEyn7ds3kjIQOTZdn/ASwb2u0WKNSWAAAAAElFTkSuQmCCUEsDBBQAAAAIAACJ2VxGPuuc2w8AADyaAAAPAAAAd29yZC9zdHlsZXMueG1s7Z1Jc9s4FoDv8ytYvmTmkNYu26l2d3mRxq5J3O7Y6ZwhErLYoQgNScVx//oBQFAC9QiSD0ScTmpyiMXlfVjeAjxw+/nXL+vI+0yTNGTx2avBT/1XHo19FoTx49mrDw/z1yevvDQjcUAiFtOzV880ffXrL//4+elNmj1HNPW4fJy+WftnR6ss27zp9VJ/Rdck/YltaMwPLlmyJhnfTB57a5J82m5e+2y9IVm4CKMwe+4N+/3pkcIkbShsuQx9esX87ZrGmZTvJTTiRBanq3CTFrSnNrQnlgSbhPk0TXmb11HOW5Mw3mEGYwBah37CUrbMfuKNUTWSKC4+6Mtf62gPmOAAQwCY+vQLjnGiGD0uqXPCAMeZ7jhhoHHsKqMBgi0KMRwV9RB/hLjGSoMsWOFwhY56QpZkZEXSVZm4jHDEsUbMDSxi/iedSXGdNtkBn9dCh2v/zc1jzBKyiDiJW6XHDcuTYC/XrPjj5cbiFd3iFa3xZKcf/cJdN2D+FV2SbZSlYjO5S9Sm2pJ/5izOUu/pDUn9MHzg9eWFrkNe/vV5nIZH/AglaXaehqTy4Er8qDzip5m2+yIMwqOeKDH9ix/8THi3D4fFnsv0cF9E4sdiH41ff7jXa6LtWnDu2RFJXt+fC8GealjvsLmbwy1Z8Ib4oSyHLDPKoxIPCgIahTwGHg2Pp8XG+63QBdlmTBWyUYXo2B7ocR6seOi6zyMoP0qXb7mt0OA+4wfOjmRZfOeHm7skZAmPkmdHp6dq5z1dh9dhENBYOzFehQH9uKLxh5QG+/2/z6Uhqh0+28b894hXX1YiDWZffLoRcZMfjYnQya0QiMTZ23BfuBT/bwEbKE1Uya8oEWOHNzhEnKIRQyGRaq2tZm4P2j5AFzR6qYLGL1XQ5KUKmr5UQccvVdDJSxV0+rULCuOAjwOD6mIAtYlj8EY0x+BsaI7Bl9Acg6ugOQZPQHMMho7mGOwYzTGYKYKTMd9khZqxjwzWXs9tHiPsuM1Dgh23eQSw4zYHfDtuc3y34zaHcztuc/S24zYHazw3n2p5N9zN4qyzly0Zy2KWUS+jX7rTSMxZMqN2wxODHk2cNNIBJo9saiDuTPOJ3G62kEm38TwTiZ/Hlt4yfNwmNO1ccRp/phHbUI8EAec5BCY02yaGHrGx6YQuaUJjn7o0bHdQkQl68Xa9cGCbG/LojEXjwHH3FUQnQWFn0Dx/XgknCR0Y9Zr4CXMwZyHO4sPbMO3eVwLiXWyjiDpi3boxMcnqnhtITPfUQGK6ZwYS0z0x0HTmqosUzVFPKZqjDlM0R/2W26erflM0R/2maI76TdG699tDmEX0cNYxaL92dxmx1EXAuw8fY8InAN2HG7Vm6t2RhDwmZLPyxKp040wLXc4FC569B+OY1oxu28W7glxN+6UFXfJOCeNt9/4u0Vz53o7nyPt2PEf+t+N198B3fBYt5m/XbtKd++0iq/Tp9gZ3T6JtPt/t7owk625heweYh0nqzA2qsQ4s+FbMdq8dzQT3texesT2ru1sdRiWn1VNIB7UU11NrojQCdf28oQnP2j51Js1ZFLEnGrgj3mcJy21Nd/nhsLXLz9abFUnDFCDazwSKmyu8d2TTuUF3EQljN3qbvV6TMPLcTTCuH9699R7YRmShomPcAC9YlrG1M6ZaKPznR7r4l5sKnvMcOX521NpzR6tHEnYZOhhkchILHJH4LDSMQydjqOT9hz4vGEkCN7S7hOa3m2TUEfGerDeRK9/icfGJxx8HsyHJ+4MkoVg2cuVUD05g2qpiul38Sf3uoe6WeU4Wjn7bZnJ5Uk51u18MLuG6TxNKuO5TBKlNPjwI+3XQ2BKue2NLOFeNvYxImobGK6zWPFfNLXiu29s9+VM8FrFkuY3cdWABdNaDBdBZF7Jou45Tly2WPIcNljzX7XVoMpLnYMVO8v6dhIEzZUiYK01ImCs1SJgrHUiYUwV0v4FHg3W/i0eDdb+VJ4c5mgJoMFd25nT4d3QRSIO5sjMJc2VnEubKziTMlZ2Nrjy6XPJJsLshRkO6sjkN6W6giTO63rCEJM+OkLOIPhIHC6Q57S5hS/GgC4vze7xdTGe3i8zlZDvHuVLyR7pwVjXBclkvByuiJIoYc7S2th9wpGT51rYmMfmgR+cq3EXEpysWBTQxtKk2X77Pn9o4rH77iyVvw8dV5t2vdqv9Ombab5QsEvaSWHOBVX0+HdaIvaNBuF0XFYXPWkxH7YWHQHjcLLyfSZQkJy0lYZnTZsn9LLkkedxSEpZ50lJyBCTr/OGKJJ8qDeG4zn52OZ7B+I5rr9sXwpXF1hnSTrLKBI/rrKjkKt6574urBVA77XzGLN/OeczyGC8yUzDuZKa09iszos7B3tPPYVq5Rt1w/Xt3c4V94Px9yzJwlXrY/pGvGz5vilPqVXJG7a9blYKMuRtbRxszonXYMSNaxx8zolUgMoqjIpKZ0jo0mRGtY5QZgQ5WcEDABSsojwtWUN4mWEGKTbDqMAkwI1rPBswItKNCBNpRO0wUzAiUowJxK0eFFLSjQgTaUSEC7ahw/oVzVCiPc1Qob+OokGLjqJCCdlSIQDsqRKAdFSLQjgoRaEe1nNobxa0cFVLQjgoRaEeFCLSjjjs6KpTHOSqUt3FUSLFxVEhBOypEoB0VItCOChFoR4UItKNCBMpRgbiVo0IK2lEhAu2oEIF21ElHR4XyOEeF8jaOCik2jgopaEeFCLSjQgTaUSEC7agQgXZUiEA5KhC3clRIQTsqRKAdFSLQjjrt6KhQHueoUN7GUSHFxlEhBe2oEIF2VIhAOypEoB0VItCOChEoRwXiVo4KKWhHhQi0o0JEnX2qK5Smu+wH+FVP4w37iMd88kq91x/0Lq2htkcVtTKz2j+KcMHYJ6/yscTRqD0kXEQhkyvUhqvqOvcYfd3zt8v6B3xavOSjbVPUoxDykimAj9tKgjWVcZ3J65IgyRvXWbouCWad47roq0uCYXBcF3SlXxb3pPDhCAjXhRlNeGAQr4vWmjjs4roYrQnCHq6LzJog7OC6eKwJTjwRnA+lJy37abq7vRQQ6sxRIxybCXVmCXVlXNtvrTQzoa32zIS2ajQTUPo0YvCKNaPQGjaj7FQN3QyrantHNROwqoYEK1UDjL2qIcpa1RBlp2oYGLGqhgSsqu2Ds5lgpWqAsVc1RFmrGqLsVA2HMqyqIQGrakjAqrrjgGzE2KsaoqxVDVF2qoaTO6yqIQGrakjAqhoSrFQNMPaqhihrVUOUnapBloxWNSRgVQ0JWFVDgpWqAcZe1RBlrWqIqlO1XEWxz5Y0cdwkTBPEDciaIC44a4IW2ZImbZktaQTLbAnqyi5b0pVmly3p2rPLlnQ12mVLQJ922VKlYu2ypUoN22VLZlXjsqUqVds7ql22VKVqXLZkVDUuW6pVNS5bqlU1LlsyqxqXLVWpGpctVanaPjjbZUtGVeOypVpV47KlWlXjsiWzqnHZUpWqcdlSlapx2VKVqjsOyHbZUq2qcdlSrapx2ZJZ1bhsqUrVuGypStW4bKlK1bhsyahqXLZUq2pctlSraly2ZFY1LluqUjUuW6pSNS5bqlI1LlsyqhqXLdWqGpct1aoaly294yKhgzdA3a9JknnuXhd3TdJVRrq/m/BDnNCURZ9p4Llt6ltUK3tPpY9jCbb80CA/P+N9Jt6Prj2tFOTvh1VAeeJNsPuIlRAWNfHU58LUbllhdblW/k5S8em0/Jx+//h4Mjsu6iKRDZXYFauuIg9AwfuPYsnyFoS397e4qlqxeGNixX5hKsX+opjLFUnyo3sjLs45bWrl6Xx8cqIu/qqPnn2idHPLy+8VG1xzNJVb+++hLcTLxngPDMfyqSz1eTTlzix/m9Pbz9GuINWPqojab8uRP2u+LScOztQ+cbz0ebmS5P7zcmL3/vNyvnD/ol6j6WR+Ko1GnixDw9kRkYFhv1vcrSJuQJjnhP0H6kYVH6jL92nfmbOxnaHRdoYubWfYwnb2/pqfV/LWBuua90eD6YW9dbUzrsGPaVzDKTSufF+zcflcr8RXb9szREf1Uu3dY5/yldqHZmd487bBZAbtTMZc70yM0TV1lmN4bVhXb/Iz2XRro84WUW5H/MdNLGz6SX3/MK9p8IUcFSde0ih6R/Kz2cZ8akSXWX500D+pOL7I3xdqlE/kzNII6JUr09s1wtzf+QdG1C1PxlFUPk8Ouzt/zrxjT9sESG7WVeGRJo2x8TAG0qQ2Aqo2VJjHQZw7GVwez0pxjltyqv4W5wm/zz1yw1KRCZyokKadkxTr7/KU09G0GDkLHvgkqf5B0vFuw/hB0jYBw9+m3A7lzOvQGLROO1RBfsjbd+iBHirjjUErTRoxdT/Wmub5h6QOm6K+L4Wxppz0f2tCWZPWaYcqyA91taa5psivb03qPTzylTWH7Sm9owdjWBq0jXU1j2yNxtbJKAzzLzF0r9h6P63Sd/jpbutgDjSomAMNbOZANUZ42MF1mutqj7qF4BRp1tr31t+lvLVqEMkfGnEwjsgkvD67MWfDP0oa4T5HzSPVR7owTcHzN9Q3BbkOI+Tp+fF8ZgpaRfI4yL/Vnm+e8zClTlH2qGKbOktuwZM6B71wTVPvlj5577m3xbq1VB4sXBUekT57sPswYRxXJIxjC+fdu+pueRL46e4IzkUdKV11d8lP+vzfXJn/ttgpPmSVp4NIa68JYKp1ply5KrDMJuPZ1bxksMKGxJvq6NVsd15+wv7I7eGR4E9erfdiVpfnpPrBrzNsX5IoXCShZpzaHmGUxSYMXH35r72ViiVfWX+5j8avb27djjz7tW21tA2XaOHyd/VirY2FY6dmutFUGfy0P5lNLhV7tRP0I0rynlAjhVA131yGET86G1zNr666hf/iBYsVSwLFofoFIvOK4cnV+GR2+gLTUc2K9xG50dgrInBzN+4WtcrLWPJde4ddqL19s8rs9PUvQxePKmc2l+ej4cngK/RrrcuWl9EuWMJT+zyPlctkeoQW3fMXT2PlDxH8VH10I9YX0axkdwtsVtLF8puVcMjNKaDX3cT/sBPvlbu/zcJg9XwABNAW8fObhc/hyWg4PP3bhU+xaLp/1eJh/x28iRE/h26MsKeD8cnIQcIvbFJghT+Kp637xQwgFh+F3pJIDQU/1DTZsO7DgufqRZ/d90RRKz4KV7fc06jmi8HxbDIpqfkpDNiTeDd5wsoXZu0mo19pmeh7MYXWy0u6No0G0nlhqTDBensx28j3ro5qz8zfOQAmWXIvxiWlRK0/9r9ThyyH8UG/zZ0aL2IWi/z/y/Qb+Oxe3ZWm09VZNfszW9Lf0VW/pU5Kt6wcqqVYNh46WjYeNiwb1y/Oa3e9/CiryF1uRmm7riaTW/PUOE+Nv+rcuOJ+pb9DjP724RgqufiV/vI/UEsDBBQAAAAIAACJ2VwWLKq00gIAAHYMAAARAAAAd29yZC9lbmRub3Rlcy54bWzVls1ymzAQx++d6TswujsC7NgOEzvTJE0nt0zSPoAihGGCPkYS/nj7SoCABDcD5FQfLJD0/2m1q11xfXOkubcnUmWcbUBw4QOPMMzjjO024M/vh9kaeEojFqOcM7IBJ6LAzfb7t+tDRFjMuCbKMwimooPAG5BqLSIIFU4JReqCZlhyxRN9gTmFPEkyTOCByxiGfuCXT0JyTJQy690htkcK1Dh8HEaLJToYsQUuIE6R1OTYMoLRkEt4Bdd9UDgBZHYYBn3UfDRqCa1VPdBiEshY1SNdTiOd2dxyGinsk1bTSPM+aT2N1DtOtH/AuSDMDCZcUqTNq9xBiuRbIWYGLJDOXrM80yfD9JcOgzL2NsEio2oIdB6PJqwg5THJ57Gj8A0oJItq/azRW9OjSl83jYLkw5Y1y11BctS50k4rh/iukt9zXFDCdOk1KElu/MiZSjPRVAc6lWYGUwfZf+aAPc1BU9mCgan2r9J2X4WhBQ4xv44dzSvLPycG/oBoWkSjGGLC+zWdJdSc4HbhSa7pODcYWHwcIOwBlpgMvCwcY10zIG6z23KygWnlOMuGk8UdzjRjOoC4GIUI584O21h5h6ViHafjcC5G0GqRRilS6XtiMrAQOOKiQ6wOWM7xW5dJxjntsgGeaCeGYve1RP0leSFaWvY12mNbsg9s3Ab95cdTIdTXjHlJkTCVnOLocce4RK+5scikr2cy0Csj4FUpYBuvyirPnR/Phd0rT6dnSyLYth+B3iHSJ2GAiggkkeYSmC6bTrOgnCeMcBHZsUfTuVovbgN/NQdlr7liddlb/6zUfJDGzxvg+8FDcHf7o+m6Jwkqct0febJdD+vgbvWzWvBJ2kYJhM3mzSSUaGIuId8K8syGI1w0L8+F9QYqNAdwew0becVwe6qGZDWh/K+3f84TmDOdsaK8u14+esU/45SF+YL1r1a3/4dTzm7vEwe1z2r7F1BLAwQUAAAACAAAidlco1EzzlUGAADOPQAAEgAAAHdvcmQvbnVtYmVyaW5nLnhtbO2b3XKjNhTH7/sUjGd20l4kSEII4dnsjj/iTjrbnU43+wAyyDENXwPYTnrVZ+mj9UkqPo1jwgKOHTvj3BAj6cc5R0c6f4vk4+dHx5aWPAgtz72+gFfgQuKu4ZmWe3998f1uckkvpDBirslsz+XXF088vPj86aePq767cKY8EP0kgXDD/so3rnvzKPL7shwac+6w8MqxjMALvVl0ZXiO7M1mlsHllReYMgIQJL/5gWfwMBScEXOXLOxlOOOxGc0M2EoMjoFYNuYsiPjjmgFbQ1RZl+k2CHUACQ8R3EYprVFEjq3aAuFOIGHVFkntRqpwjnQjoW2S1o2kbJNoN9JWOjnbCe753BWNMy9wWCQ+Bveyw4KHhX8pwD6LrKllW9GTYAKSY5jlPnSwSIwqCI5itiZosuOZ3FbMnOJd9xaB28/GXxbjY9P76fjsUozgdrPHisfpMn+M7DDKxwZNYpcOH3vGwuFulERNDrgt4ui54dzyi93B6UoTjfMcsqwLwNKxe8XOBhsutZe2tnE6DWtgE/OzuXPs1PJ6IgQNZjNGFCOamLD5zNwSR2Tw+sGdQlMKLmy4+eQAtAUgBm9YLHIGzRiysV7dMcdquKxyDik4llnidDOmBDAXrRBIye2IL/HwEis0I3PeDpfPkRyPZRGbs3C+SZw13AhyIi4R0wSzPeOhzOTtgqYWwCenNIf+/W4L9dfAW/hrmrUb7Xa9Za/cdg4C8jwr/HA3Y77NmS92csfo3967XsCmtrBILF9JrEApmQEpXQLxRUpXlZTnj5RPu5RkpxRvib1PQgWyaRgFzIi+Lhxp49OtWEqgF8P7ARcKMohvpoJxMIt4MAw4e4i7xBQ3jB/bXzKRViD5QXpPjluchR1ZX/iS23dPPs/7zJ+mgWX+HrfZcVvaN3J8u0zBFClpi72MGyxxSY3qR75tpJ0gHd4kNiQ25sNhOk5o3IlT3DS5YTnMLpB3osLlbR/gVXH/NyO/a/NZlN72/wgSE0WEsmveRzwjtsj3xPxqCMTd5XVHy40DE3PSVvFhztz7WJ73FJL3zuhBdpl4bhSKnoZA3lkOD6WvfCX96TnMzQYkPeXE2ufxgev4TLKfXrtY1AbiVWxEJ2CjcgI24hOwUT0BG8kJ2KidgI30KG2UNwrbD6se7Fr1iEbxK1S9wQ38YdVTxmTUsOrZ3ooHX3gkrK+M+M8f4C/n0ncufefSdy59R2rjufQdqPShLqUPqvpAJXS4W+mDwxHWxwDVlz4MdFH9Jof7wrdTEZtbbhRbMWPC8VblK3UU6skd7kYsspY87vE6Nf8Dau08xLjW+x9Wu8yl4S4uFXm+7ZFS5VFg3c9fdglBsukSpA1cUirSsZtLtemJW88QorTDDOHDJZ3a2iXhQQeX1IMlHWmfdFhBHZKOHCbptNYzpIIu24J2uKSj7V3SSAeX6MGSTm+fdATTRknXUi4oneSCBiFC48FuckEfKpRAMKiVCxirAzpq/E35leWC/myhZ9+QV/2/tmftZQ3BQsOytrWeaOEsjAahxSob5wMR88qWKuVYpVVExHxmxH8fkhl7mR3Gr4oggsyh8O/8FsL5nVH4/J7N1izuXn7/tulEcWtqmcJyFlx+G7TSTPpgQggckQrZPV3YNo8qJ/a/f/5tLYU0nVbNbAshuKdolOQWpkOENQ3sPRqIaOQ4o1FWajcQjCncfzQUVcXHGY2S0NMmYzABkO49GlioneOMRkkjEqLeDIG6/9xQFVhZEd4+GiV5SUZineCb0d6jQSA90l20fNwERwNtkr0r32c0NECOdBctCduBPsFUJYP9R0PHR7OLttTEuJMmnqhCFOMdj9BE7RmpN3BUr4lB8uXkVb4uNntx9EZHaJmj7+kILXPpPR2hpS69myO0fSfdGxyh7Tnp3uIIbZ9J9wZHaPtOujc4Qttz0h3PEZraRS4oOsUYj9Td5AK+GRI0wvVv3Ig2opNxdqhygm/chLxrIxqK0+jTFQnn92zHLhLO79lOQSSc37Mdu0h4T+/Z3EQcuKW/QI3/laNvLpJ/9EhuqipSAQLZkf6Gjsityx/mVkBRFVTTKQS6RmuYsIapVDEJhTpQFUBeZqIaJq5iqopCEKQKepmJa5hqZUChChRAFeVlplrDJJVMhHSAdIRrnFfKULn0j9if/gdQSwMEFAAAAAgAAInZXB89Ltt9AAAAzQAAABMAAABjdXN0b21YbWwvaXRlbTEueG1srYxBCsMgEAC/UnxANvTQgzSFQI+lBLz00IvaNQrqim6g+X0t/UKPMwNzNlLRVi22wzvF3KSZhGcuEqBZj0m3gQrm3hzVpLljXYGcCxavZLeEmeE4jicwwcRAa9XF7+I3+89KYUTL+FK8R5zEc17m4aFuPXzFXacuuxNw+QBQSwMEFAAAAAgAAInZXD7K5dW9AAAAJwEAAB4AAABjdXN0b21YbWwvX3JlbHMvaXRlbTEueG1sLnJlbHONz7FqwzAQBuC9TyG0aKplZyihWPYSAtlCcCGrkM+2iKUTuktI3r6iUwMZMt4d//dzbX8Pq7hBJo/RqKaqlYDocPRxNupn2H9ulSC2cbQrRjDqAaT67qM9wWq5ZGjxiURBIhm5MKdvrcktECxVmCCWy4Q5WC5jnnWy7mJn0Ju6/tL5vyG7J1McRiPzYWykGB4J3rFxmryDHbprgMgvKrS7EmM4h/WYsTSKweYZ2EjPEP5WTVVMqbtWP/3X/QJQSwMEFAAAAAgAAInZXOvSlNzaAAAAVQEAABgAAABjdXN0b21YbWwvaXRlbVByb3BzMS54bWydkEFrwzAMhe+D/geje+rMddu1xClLTaHXscGurqMkhtgOtlM2xv77XHZaj7tIvCek76Hq8GFHcsUQjXcCHpclEHTat8b1At5eT8UTkJiUa9XoHQpwHg714qFq475VScXkA54TWpINk/tZCvhaHTf8xLbHQspc+Jqti2fZ7IqGsYZzxlc7uf0GktEun4kChpSmPaVRD2hVXPoJXR52PliVsgw99V1nNEqvZ4suUVaWG6rnjLfvdoT6lud3+wW7+Ffeos3B/JdyMZfR+D6oafgEWlf0DkXvX1H/AFBLAwQUAAAACAAAidlcXmQP0NECAAB8DAAAEgAAAHdvcmQvZm9vdG5vdGVzLnhtbNWW226bMBjH7yftHZDvUwM5FjWp2mSZeje12wO4xgRUfJBtcnj72RATWrIK6NVyEQeb/8+fv5Nzd3+kubcnUmWcLUFw4wOPMMzjjO2W4M/v7WgBPKURi1HOGVmCE1HgfvX9290hSjjXjGuiPMNgKjoIvASp1iKCUOGUUKRuaIYlVzzRN5hTyJMkwwQeuIxh6Ad++UtIjolSZsM1YnukwBmHj91osUQHI7bACcQpkpocL4ygN2QKb+GiDQoHgMwJw6CNGvdGzaC1qgWaDAIZq1qk6TDSlcPNhpHCNmk+jDRukxbDSK10ou0E54Iws5hwSZE2j3IHKZJvhRgZsEA6e83yTJ8M0585DMrY2wCLjKom0HHcmzCHlMckH8eOwpegkCw660e13poeVfrzUCtI3m1bs90tJEedK+20sovvKvmG44ISpkuvQUly40fOVJqJujvQoTSzmDrI/jMH7GkO6s4WdCy1f7W2TRWGC7CL+efY0byy/HNi4HeIpkXUii4mvN/TWUJNBl82HuSahnODjs3HAcIWYIZJx8vCMRZnBsSX6racrGNZOc6s5mRxgzPMmAYgLnohwrGzww5W3mCpWMdpP5yLEbRapFGKVPqemHRsBI44aRCrBMs5fmsyST+nTWvgiTZiKHZfK9SfkhfiQsu+Rnu6tOwD63dAf/YxK4T6mjEvKRKmk1McPe0Yl+g1NxaZ8vVMBXplBLyqBOzgVVXlufzxXNi9Mjs92xLBqvEv0DtE+iQMURGBJNJcAjNl62kUlC8Ko5xEdu3JTI79yWYebkNQzpo7VtvZ+fljpeYvafy8BL4fbIP140M9tSEJKnLdXvllp7aLYD3/UW34S9pBCYTN6c1LKNHE3EK+FeSZjUc4qR+eC+sOVGgO4OoO1vKK4c5ULcnqhfLbnf+qLzBnOmNFeX29fPSLf8Uts8cgeNisp/+HW64e7zMXNR7U6i9QSwMEFAAAAAgAAInZXJa1reLCBQAAUBsAABUAAAB3b3JkL3RoZW1lL3RoZW1lMS54bWztWU2P20QYviPxH0a+t46TOM2umq022aSF7bar3bSox4k9sacZe6yZyW5zQ+0RCQlREAcqceOAgEqtxKX8moUiKFL/Aq8/koyTyTbbLqKozSHxjJ/3+8PvOJev3IsYOiJCUh63LOdixUIk9rhP46Bl3er3LjQtJBWOfcx4TFrWhEjrytaHH1zGmyokEUFAH8tN3LJCpZJN25YebGN5kSckhntDLiKsYCkC2xf4GPhGzK5WKg07wjS2UIwjYHtzOKQeQf2UpbU1Zd5l8BUrmW54TBx6mUSdIsP6Iyf9kRPZYQIdYdayQI7Pj/vknrIQw1LBjZZVyT6WvXXZnhExtYJWo+tln4KuIPBH1YxOBIMZodOrb1zamfGv5vyXcd1ut9N1ZvwyAPY8sNRZwtZ7Tac95amB8stl3p2KW6mX8Rr/2hJ+o91uuxslfG2Ory/hm5VGfbtawtfneHdZ//Z2p9Mo4d05vrGE713aaNTL+AwUMhqPltBpPGeRmUGGnF0zwpsAb04TYI6ytezK6WO1KtcifJeLHgCy4GJFY6QmCRliD3AdHA0ExakAvEmwdiff8uTSVioLSU/QRLWsjxMMFTGHvHz248tnT9DJ/acn9385efDg5P7PBqprOA50qhfff/H3o0/RX0++e/HwKzNe6vjff/rst1+/NAOVDnz+9eM/nj5+/s3nf/7w0ADfFnigw/s0IhLdIMfogEdgmEEAGYizUfRDTHWK7TiQOMYpjQHdVWEJfWOCGTbg2qTswdsCWoAJeHV8t6TwYSjGihqAu2FUAu5xztpcGG3aTWXpXhjHgVm4GOu4A4yPTLI7C/HtjhPIZWpi2QlJSc19BiHHAYmJQuk9PiLEQHaH0pJf96gnuORDhe5Q1MbU6JI+HSgz0TUaQVwmJgUh3iXf7N1Gbc5M7HfIURkJVYGZiSVhJTdexWOFI6PGOGI68jpWoUnJw4nwSg6XCiIdEMZR1ydSmmhuiklJ3V0MvcgY9j02icpIoejIhLyOOdeRO3zUCXGUGHWmcahjP5IjSFGM9rkyKsHLFZKuIQ44Xhnu25Sos9X2LRqE5gRJ74xF0bdLHTii8WntmFHox+fdjqEBPv/20f+oEW/DM8lUCYvtdxVusel2uPDp299zd/A43ieQ5u9b7vuW+y623FX1vG6jnfdWWx+KM37Rygl5SBk7VBNGrsusK0tQ2u/BZrbIiGYDeRLCZSGuhAsEzq6R4OoTqsLDECcgxskkBLJgHUiUcAnHAGsl7+wsScH4bM+dHgABjdUe9/Ptmn4wnLHJVoHUBdVSBusKq116M2FODlxTmuOapbmnSrM1b0I1IJwe+51GNRcNGYMZ8VO/5wymYTn3EMkQ+6SIkWM0xKmt6bbmq72mSduovZm0dYKki6uvEOeeQ5QqS1Gyl8uRxeUVOgat3KprIQ8nLWsIQxRcRgnwk2kDwiyIW5anClNeWcyLBpvT0qmsNLgkIhFS7WAZ5lTZrel7k3iuf9Wtp344HwMM3Wg9LWpN5z/Uwl4MLRkOiadW7MyXxT0+VkQchv4xGrCxOMCgdz3PLp9KeGZUpwsBFVovEq9c+UUVLL6fKaoDsyTERU9qarHP4dn1TIdspalnr9D9NU2pnaMp7rtrSpq5MLbW/OwsBWOAwCjN0ZbFhQo5dKEkpF5PwOCQyQK9EJRFqhJi6dvmVFdyNO9bOY+8yQWhOqABEhQ6nQoFIfuqsPMVzJyq/nydMir6zExdmeS/A3JEWD+t3kZqv4XCaTcpHJHhFoNmm6prEPTe4smnvmLyOX08mAuqn2UWqWtNX3sUbLyZCmd81FbNFlfdtR+1CRw+UPoFjZsKj83n2z4/gOij2USJIBEvNIvym20OQOemZlzK6t8do+YhaK6I93kOn5qzayucfbq413e2a/C1e7qr7eUStbWDTLZa+teJD+6C7B04KI2ZkvmLpHtw1OxM/y8APvacdOsfUEsDBBQAAAAIAACJ2Vx8SMsSlAMAAD8+AAAUAAAAd29yZC93ZWJTZXR0aW5ncy54bWztm9tu2zgQhu8X6DsIum/E88FoUiAtulige0APey9LdCxUEgWJies+/Y4sO5GbYlEtsAkvBgEiivL8IecjhxzKefX6a1Mnd64fKt9epvSCpIlrC19W7c1l+vnTu5cmTYaQt2Ve+9Zdpns3pK+vXvzyarfaufVHFwJ8ckhApR1WTXGZbkPoVlk2FFvX5MOF71wLDze+b/IAt/1N1uT9l9vuZeGbLg/VuqqrsM8YISo9yvQ/o+I3m6pwb31x27g2HOyz3tWg6NthW3XDSW33M2o735dd7ws3DNCfpp70mrxq72WoeCTUVEXvB78JF9CZY4sOUmBOyaHU1A8CcpkAeySgCvd1mYY5amRgOdepymU66l6nKmc6/60xM4HydpEE46d2jJfRfKY1lKHcLpM7McpG2zzk23zYnitu6mWKYqY4DbDaF1/mmm6Z0+S94L4ZGTbF6reb1vf5ugYlGJUJDKzkIJxMZMdLMg2W5OSW5NSb5OD09Armb1ndDcdrsluNI4IJoq2i1hyer325f3t4dpeDF2iajbUwe9+7TTjVkvvaD9XN9gfVn3z3uPLah+Cb7+qhHddlP5bCg00LUSeFm+Hb+Lmx0OWFO5YLX3sIFvlt8JNEPWvZMsv1WYuW2fbzni8xzR46PRXPcXBqldUMAiPiiAEH55YaJhFHFDiEVIxaxi3iiAGHJvAjhBaIIwocnEK0sgqX8ihwGKGlFYJQxBEDDkth6TBS4toRBQ5KKFfEMobT48l5THngm21Vl9/tr5iQQtLjHEHvP633rSSECmkoev//j0XZGYZ/rz2PW4IbJRnhGLeimTmUMWmYVhxnzjN4X4PvqdKKofcjjlsUdlyMcYH7rTj2v1QJywn8Rh5R8IDsUFJuKPKIgwen1BJhCObrkfCwVlqmjUQeUfAQsOcywmiCPOLgATCk4RZfFcaTmUhrKCHsGLPQ+0+clVuiiIbUHL0fcV4ohVKwqhvcZ8WxjkiriNHU4FvcOHgoofiYqeN5byw8IFppKjTyiIMHZOmSQdBCHlHw0ERzJbnEc95IeAhjhCCSIY8oeBitqSLU4HoeUaYoxtNeJS1+9eE53M8Mk4IbatD78SbqjIwnjMxyfEEVxULCKBOCaiXw4CSiSEa0UUxLjd9FeZZ1fHxHSKUR6P7IVpJj7dgE34Wqqb65d76/7v1ucP3UMlfv/2z//v394S6va7/7649fp788+7fvq38AUEsDBBQAAAAIAACJ2VxoAH4jcQIAABUKAAASAAAAd29yZC9mb250VGFibGUueG1svZTfbtsgFMbvJ+0dEPetseO4adS0Wrtm2s0upu4BCMYxqgELSNO8/Q74T11lUUulLpFl+8D5mfPxHa5unmWDnrixQqsVTs8JRlwxXQq1XeE/D+uzBUbWUVXSRiu+wgdu8c311y9X+2WllbMI8pVdSrbCtXPtMkksq7mk9ly3XMFgpY2kDl7NNpHUPO7aM6ZlS53YiEa4Q5IRUuAeY95D0VUlGP+u2U5y5UJ+YngDRK1sLVo70Pbvoe21KVujGbcWapZNx5NUqBGT5kcgKZjRVlfuHIrpVxRQkJ6S8CSbF8A8DpAdAQrGn+MYi56RQOaUI8o4TjFyRDnhfGwxE0C5i0Jks2Ed/ubTJyxburKOww17lPhc6mhNbf2aWDVxxHxC7AzWaPY4ZfI40eYj8CD9Hkq2/LlV2tBNAyRwJQJjoQBG3c76G+rMggZZ0FANCqLj675z0X6pqATQg5Dcol98j35rSVWY0FKlLU9hzhMFGYgXrCAzMic5XBk85TjxE1lNjeVunEi6cEWlaA5D1ARuGGiFY/UQf6JG+GK6ISu2MLCzG7LC94SQ7H69xl0kXeE7iFws5rd9JPPfCr/LPjIbI8RHWOCE17TjsMAZ58A3k06JI0XuaCM2RpxQYh0U8P8cdMiilLB7YW2cEvmREnBAZfnFf1HiB905KOCEErdBiby/wBWfqgRU7Zc7e1FiWuUrJcibSoAWsZ6QYAl6QgnfFV13FNGe+Fh3kGLqiTx4YoxkYVHvUyK9jPTEA61hxSctUYS28FLkn98c6b+OiYIcHxPZW82RxjfHt9Zpiz+xvLCF2eLiyPGzDzj+7X3uH+z1X1BLAwQUAAAACAAAidlcYPIbzb8IAAAbIgAAEQAAAHdvcmQvc2V0dGluZ3MueG1spVrLcts4Ft3PV6i88WYU4w1SFaeLJIjuTCU9XeN0zZoSKYtlPlQkZcc9Nf8+l6Jo2cnxVNy9MomDe3DfAES//+lrXS3ui64v2+b6kr9jl4ui2bR52dxeX/7+xS+Dy0U/ZE2eVW1TXF8+Fv3lTx/+9v5h1RfDQLP6BTE0/areXF/shmG/urrqN7uizvp37b5oCNy2XZ0N9NrdXtVZd3fYLzdtvc+Gcl1W5fB4JRgzFyea9vri0DWrE8WyLjdd27fbYRRZtdttuSlOf2aJ7kfWnURcuznURTMcV7zqiop0aJt+V+77ma3+s2wE7maS+/9nxH1dzfMeOPsBcx/aLn+S+BH1RoF9126KvqcA1dWsYNmcF1bfET2t/Y7WPpl4pCJxzo5PzzXXbyMQ3xGYTfH1bRzBieOKJJ/zlPnbeMwTT5k/4/lzyjwjyA9vohBy1mP8M4o/4+rzId+9jW6O0dUomw3ZLut3Lxm31dsY1TPGKcGqdnP3nLN4m9P0E+FjfY5h/71aIKsn6FO57rLu8XlK15vVx9um7bJ1RepQai8oOxdH7RZTeox/FlPGLWbfLmaXLI6Ru/hALe2Ptq0XD6t90W2orq8vOGMXVyNA1dRub4ZsIMZVvy+qauyPF5uqyEiBh9Vtl9XU2uaRo0xebLNDNXzJ1jdDu6dJ9xnZacWJMu+yByL5uSvzX9qu/KNthqy62WcbGpwncz5PLvt9lT2eJ7qzdErd+3GWENP8zS7rss1QdCfChIS6tppn5e2v7ZBQD+6oRUwSu7y72WX7wk1a9x/et6t+HDiZ0S/uV8VX8kmRl8PFot+XeZ1R/QqmjzpeIYqH1bZth6Ydit+652+kx1izSz6t/c3wzPdStmjy716+4Xk5OtO8EJw2nvPTzbSJkUiT1ZQ9Lzamz21ejNE9dOWPp/nFU/DmWMCFDn3xb5pNNSG/UKju4nYY2vqXx/2uaI670l9Y+GT42Vba3fN+fvgXuXWeypgPeGLTSdMRPSPUsyPtMGKYVBARIo4SiEiW2ggiWnCDZbRSCdbNGOUkRKwwicCIFjKGSMiUxvZElifYB5FNQ2xPwr3CMomJbAARx6zXGOFWM4ikwrsQIl4mmI1znsSQjXMVMag1F4LHmE0IZQ1EFPcSRo4bEVsYOR5qGVmIRNYyGDkeC2OwBrFwHGvgbJp4iKTMc6yBJ7/BaAvJDOcQUSJi0NdCixBrLSxLAqibsDxmMHdEIIWAeSBCLrGvRSSTEGtAGS/xOjGzCtuTcI1zVDgmLbbHMeKDSKpFimW8JD6MKM2hD6TkOoL2SGl8gGWIC9sjjWAGy1gCoNYyFNJAS2WoYgZzVEbSKay1U6mGMooLyWHnU9y4AGqgJIs99KhSnGPvKCu8hrWgQh6nmC20JsW6xVYJLONYImFHUl4FuJMrr62Ce4kWWuJ809R2Ytj9tWEJrh9tZBRCDbS1oYfe0YF9jS3WPsJsCUUB9l5CDH8FMVZgHzidcphV2pk4wRp46Q1EqBQC3P2N1FQNEDFMpTAKtKF7C6NAe6ZUmC2WmsHeazzlCGSz1JdxlVhmnYORs9xIBSNnhZV4R7dKWYc1UDZNoT1W2wBnrzU2CbCM1amFPrABCwJYPzYyHvcdG2upYNUToiKYb4SEBnY+66wJsEdT6/E+R8cgjus0oGMi7nyB0CH2aKAEx/tcoI13GDFaY48GEZ0pMBJL2k4g4qgtQx8E1OFT6OuQij6G+RZyKjq4M4WceiL0TshNhOMT0nEDn6JDyRPcxUIjOO4uoZFJDGshDOi2jteJuIqh38JIc4/tiXQUYg0i61MsE1shsQapMgxHIbUK79uhlxpXSUg7U4DX8SoJYf2EXisPYxoxrvHtgxCLb20RXbRCGIVIahPATh5J6/CtIArIbRgJxzMXRCIhcJ1GkYrx+TqimxHub5ETIoG+jlLKKqxbKkQAe2/MpdawFkixVEN7YsFkArWOpU3xuSpW3Bm4y8RK05aBEauwD2JrJK6sODCJwVrTWUxgH4SkApaJjMV7cBxTd8EaJIJL2BMT6v8p7CEJpxMkzJBECJNiNs05PqWRA4SBuiV0m8Kdb0RSmDtUpNbgdSIpAqxbbG2ELXWa476TOMMF1tqZAHvU0c0Rd2VHl1D8W43j7JU+6riJQ1hZTnDtYYd1UrgYy1CfYDDjnVQO56iThvwDETNeQCBiqYLxOiF7pfe6UCQSy8SG498CnKNgYyTl0sMMcSmVPbbUW9qgEZIyk+KzZcqViGEUqL0ZAddJtUod1Do1zCvog9Qyjus0pbvMKxoEPEyxBtSR8BmWWqXDkUtjqfA+lzoe4SikTskY9tHUWbpkQCTlDJ+IU9q3DY6C11QoCPFMcnwz8nRej+E6XlBiQd28ZJxBSwkxryCWjnCY7dVfdX2glcb2RHSnhPHxsQyxR71TwsFo+9SE0yntaoL6D+/r1fiRdPwhfnrybTMs6kkiyep1V2aLz+Nn1Ktxxrq7i8tmxtfFtu2K58jNYT2Dy+UE9HVWVb7LNse38aOJK7bH5+pz1t2e2dg0v4OjebH9x2YeGz8EFd3PXXvYT+hDl+0/NnlxVp0rdZIsm+FTWc/j/WF9M0s1Wff4DDo0+T/vu6N3zk55WA27oi5Gr3zKzh+Bimb5+8344/66zMvri6FYfvx18vim6m7GrwLF52y/nz4urG/59UVV3u4GPooM9JZn3d3xZX0rTpg4YmLCji/ZZjSUZp8ezmNiHns2T85j8jym5jF1HtPzmD6PmXnMjGO7x33RVWVzd33x9DiOb9uqah+K/Jcz/t3Q5ITjt6zoMLTz96zfys1woIcj2v+Vb1qn2VX22B6GF3NHbJy8f8kwfnU9fYO7eiF8rIL+249jebEpKWNvHuv1+dvcu8msquyHm2KfddnQdjP29yPGFRm9+UjFRk/HcWMDzXQ0tRyun2A9wf/RzjOmTLCkVh8vVZjoZcy9WUorQuOUcWEc/fdUq/O/dXz4H1BLAwQUAAAACAAAidlcLUgZQOwEAACXFwAAEAAAAHdvcmQvZm9vdGVyMS54bWztmN9v4kYQx9/7V4x4SasS/BODycEVDKRIXA6FnCrlbWMvsXW219pdQjjdQ/+H/of9SzqLsYEjPRlOqi7qESmOZ3c+ntn9zrDOm7fPSQxPlIuIpd0Lo6FfAE19FkTpY/fiw934sn0BQpI0IDFLafdiTcXF295Pb1adheSAzqnorDK/WwulzDqaJvyQJkQ0ksjnTLCFbPgs0dhiEflUWzEeaKZu6Ju/Ms58KgQ+ySPpExG1Lc5/rkYLOFmhswLamh8SLunzjmGcDGlqrtY+BplngDBD0zhGWSejHE1FdQSyzwJhVEek5nmkF5JzziOZx6TWeSTrmNQ+j3Qkp+RY4CyjKQ4uGE+IxFv+qCWEf1xmlwjOiIweojiSa2TqToEhUfrxjIjQqyQkVnAyoaUlLKCxFRQU1q0tedrZ+l+W/ir0Tu6/vZQeNK72WHycq9FnGQtZ+PIqa5e7D5m/TGgqN6umcRrjOrJUhFFWdofkXBoOhgXk6WsL8JTEtbKzGRVL7d9a2zDfhh2wSvjbvUviPPKvEw29wm4qROlRJYTDZxaRJKjg3YPPWpq9xTUqNp8CYB4BHJ9W/LIoGO0tQ/N31a04UcWyKjhOyYmCPc55wewBguVJCNMq4lAX5b7HEoEMwtNwxR5pypdIEhIRHhIXFRtBQbT3iLnAYuZ/3GfS0xatWQLXyd4eZo/fVqjXnC2zHS36Ntpk17JX6WkJ6s6XqsjEtwUzD0mGnTzxO5PHlHHyEGNEWL6AFQibHYC8BNQF8qqCQj9QbDts1AmqJdZ6eP7L0GB3MsLJBGvHdvue1R+2ahsrfnVKZbU80xs0x8rawSNmcNut6Xp7YFmWU5pmXBmH45aL4MI4pAuyjKUaGdgtu11On+2ZNlHM+OYyl+sY0+g8EdTnmDFJeU1TIzyfwMcslQInEOFHuLn9TDKhoGE/FeX9xuNh89tnMeMFsOmqHzVd4vpTT411aypLozTeRSnG23dyiPhU+BqlxROHNm0bnVamwV9clFeSBgJ63u3EG3y4v4fr6ftBfwqjm7vR7ex2Mh/NYTp5N7kbDdV8mXvlqR+LqWW2bNcbu4diam0/B2I6VMf3J6ZXL6P/VkCq5XVERnzsUBmngvInWuvd0segAe/zowyMntWIgMEyitV7ah3cS0Ovw4GwcC04Y4sRV7HLdYY8kdE4nks82G8389WuUm+AX8zBkouQhJWyHqXBa8/5ZWXAPVkQDu8IRxlMGrMGjIQkktbhhq5gSOMwqoOH7wCcxPktXIJh6Lpu4vyb4aRfoR3Z/bbnDD3vsB05fWM8bA/GP9rR/60deYxnu3ZkGDKEccwYr8MsZhJuGDTbdh37Ex6+VKPqc58EKMk5WZM0gltGAnifZUxEksKM4GuumovyzJisw5StKM/NdXi3TB5IBF4k13iDVc/xQI5ihr///AtslLFhwWfwJjcd+OBYrusOp+rMPZt6tung5wpmfRzr96ee59hm8/cruJ7fqelf9A2+r2JzoLds/WUVv4Zt65mtXcbG/aTKkUN3Bp7dMr84cujW2HbHhzX+vZ9ff9T4aWK5ozHNQpZiLf/qGtDW22bTdB3XrW/v3aYBhtNsNa9gTJ7zWT/rv7R1MJ2WC7pjWjBKSBR3gARJlP7m88h/WH76pF7OruAP+qAqvQOr1aqxP/SCLLXN/9V7/wBQSwECFAAUAAAACAAAidlc446IOKgBAABiCAAAEwAAAAAAAAAAAAAAgAEAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQIUABQAAAAIAACJ2Vw52Hxe6QAAAE0CAAALAAAAAAAAAAAAAACAAdkBAABfcmVscy8ucmVsc1BLAQIUABQAAAAIAACJ2VzvKBONygEAANkDAAAQAAAAAAAAAAAAAACAAesCAABkb2NQcm9wcy9hcHAueG1sUEsBAhQAFAAAAAgAAInZXJa7M4xtAQAAvwIAABEAAAAAAAAAAAAAAIAB4wQAAGRvY1Byb3BzL2NvcmUueG1sUEsBAhQAFAAAAAgAAInZXEqRSNTCBAAA5hQAABEAAAAAAAAAAAAAAIABfwYAAHdvcmQvZG9jdW1lbnQueG1sUEsBAhQAFAAAAAgAAInZXEWHAQ9EAQAATQYAABwAAAAAAAAAAAAAAIABcAsAAHdvcmQvX3JlbHMvZG9jdW1lbnQueG1sLnJlbHNQSwECFAAUAAAACAAAidlc/RIfDx0FAABRFAAAEAAAAAAAAAAAAAAAgAHuDAAAd29yZC9oZWFkZXIxLnhtbFBLAQIUABQAAAAIAACJ2VyfaapxswAAACABAAAbAAAAAAAAAAAAAACAATkSAAB3b3JkL19yZWxzL2hlYWRlcjEueG1sLnJlbHNQSwECFAAUAAAACAAAidlcYSGooL8dAAC6HQAAFQAAAAAAAAAAAAAAgAElEwAAd29yZC9tZWRpYS9pbWFnZTEucG5nUEsBAhQAFAAAAAgAAInZXEY+65zbDwAAPJoAAA8AAAAAAAAAAAAAAIABFzEAAHdvcmQvc3R5bGVzLnhtbFBLAQIUABQAAAAIAACJ2VwWLKq00gIAAHYMAAARAAAAAAAAAAAAAACAAR9BAAB3b3JkL2VuZG5vdGVzLnhtbFBLAQIUABQAAAAIAACJ2VyjUTPOVQYAAM49AAASAAAAAAAAAAAAAACAASBEAAB3b3JkL251bWJlcmluZy54bWxQSwECFAAUAAAACAAAidlcHz0u230AAADNAAAAEwAAAAAAAAAAAAAAgAGlSgAAY3VzdG9tWG1sL2l0ZW0xLnhtbFBLAQIUABQAAAAIAACJ2Vw+yuXVvQAAACcBAAAeAAAAAAAAAAAAAACAAVNLAABjdXN0b21YbWwvX3JlbHMvaXRlbTEueG1sLnJlbHNQSwECFAAUAAAACAAAidlc69KU3NoAAABVAQAAGAAAAAAAAAAAAAAAgAFMTAAAY3VzdG9tWG1sL2l0ZW1Qcm9wczEueG1sUEsBAhQAFAAAAAgAAInZXF5kD9DRAgAAfAwAABIAAAAAAAAAAAAAAIABXE0AAHdvcmQvZm9vdG5vdGVzLnhtbFBLAQIUABQAAAAIAACJ2VyWta3iwgUAAFAbAAAVAAAAAAAAAAAAAACAAV1QAAB3b3JkL3RoZW1lL3RoZW1lMS54bWxQSwECFAAUAAAACAAAidlcfEjLEpQDAAA/PgAAFAAAAAAAAAAAAAAAgAFSVgAAd29yZC93ZWJTZXR0aW5ncy54bWxQSwECFAAUAAAACAAAidlcaAB+I3ECAAAVCgAAEgAAAAAAAAAAAAAAgAEYWgAAd29yZC9mb250VGFibGUueG1sUEsBAhQAFAAAAAgAAInZXGDyG82/CAAAGyIAABEAAAAAAAAAAAAAAIABuVwAAHdvcmQvc2V0dGluZ3MueG1sUEsBAhQAFAAAAAgAAInZXC1IGUDsBAAAlxcAABAAAAAAAAAAAAAAAIABp2UAAHdvcmQvZm9vdGVyMS54bWxQSwUGAAAAABUAFQBbBQAAwWoAAAAA");
        var len = binary_string.length;
        var bytes = new Uint8Array(len);
        for (var i = 0; i < len; i++) {
            bytes[i] = binary_string.charCodeAt(i);
        }
        var zip = new PizZip(bytes.buffer);
            var doc = new window.docxtemplater(zip, {
                paragraphLoop: true,
                linebreaks: true,
            });

            // Format amount
            const amtStr = 'Rs. ' + (rowData.amount || 0).toLocaleString('en-IN', {maximumFractionDigits: 2});
            const d = new Date();
            const dateStr = d.toLocaleDateString();

            doc.render({
                client_name: rowData.client_name || "N/A",
                brand_name: rowData.brand_name || "N/A",
                campaign_name: rowData.campaign || "N/A",
                amount: amtStr,
                date: dateStr
            });

            var out = doc.getZip().generate({
                type: "blob",
                mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            });
            saveAs(out, "Invoice_" + (rowData.client_name || "Client").replace(/[^a-z0-9]/gi, '_') + ".docx");
        } catch (error) {
            console.error(error);
            alert("Error generating DOCX");
        }
        
        btn.innerHTML = originalText;
        btn.disabled = false;
}

function handlePdfGenerateClick(e) {
    const btn = e.target;
    const id = btn.getAttribute('data-id');
    const rowData = globalData.find(item => item._id === id);
    if (!rowData) return;

    // Show generating state
    const originalText = btn.innerHTML;
    btn.innerHTML = '⏳...';
    btn.disabled = true;

    // Create a temporary hidden div with the invoice HTML layout
    const invoiceDiv = document.createElement('div');
    invoiceDiv.style.position = 'absolute';
    invoiceDiv.style.left = '-9999px';
    invoiceDiv.style.top = '-9999px';
    invoiceDiv.style.width = '800px';
    invoiceDiv.style.padding = '40px';
    invoiceDiv.style.backgroundColor = 'white';
    invoiceDiv.style.color = 'black';
    invoiceDiv.style.fontFamily = 'Arial, sans-serif';
    
    const amtStr = 'Rs. ' + (rowData.amount || 0).toLocaleString('en-IN', {maximumFractionDigits: 2});
    const dateStr = new Date().toLocaleDateString();

    invoiceDiv.innerHTML = `
        <h1 style="text-align: center; margin-bottom: 30px; color: #333;">INVOICE</h1>
        <p><strong>Date:</strong> ${dateStr}</p>
        <div style="margin-top: 30px; margin-bottom: 30px;">
            <p><strong>Billed To:</strong></p>
            <p style="font-size: 1.2em; font-weight: bold;">${rowData.client_name || "N/A"}</p>
        </div>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
                <tr style="background-color: #f2f2f2;">
                    <th style="border: 1px solid #ccc; padding: 10px; text-align: left;">Description</th>
                    <th style="border: 1px solid #ccc; padding: 10px; text-align: right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="border: 1px solid #ccc; padding: 10px;">
                        <strong>Campaign:</strong> ${rowData.campaign || "N/A"}<br>
                        <strong>Brand:</strong> ${rowData.brand_name || "N/A"}
                    </td>
                    <td style="border: 1px solid #ccc; padding: 10px; text-align: right;">${amtStr}</td>
                </tr>
            </tbody>
        </table>
        <div style="text-align: right; margin-top: 30px; font-size: 1.2em;">
            <strong>Total: ${amtStr}</strong>
        </div>
    `;

    document.body.appendChild(invoiceDiv);

    var opt = {
        margin:       1,
        filename:     'Invoice_' + (rowData.client_name || 'Client').replace(/[^a-z0-9]/gi, '_') + '.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(invoiceDiv).save().then(() => {
        document.body.removeChild(invoiceDiv);
        btn.innerHTML = originalText;
        btn.disabled = false;
    }).catch(err => {
        console.error(err);
        alert('Error generating PDF');
        document.body.removeChild(invoiceDiv);
        btn.innerHTML = originalText;
        btn.disabled = false;
    });
}

function handleEditClick(e) {
    const btn = e.target;
    const id = btn.getAttribute('data-id');
    const item = globalData.find(d => d._id === id);
    if(!item) return;

    document.getElementById('edit-id').value = id;
    
    // Populate form
    document.getElementById('new-region').value = item.region || 'India';
    document.getElementById('new-client').value = item.client_name || '';
    document.getElementById('new-campaign').value = item.campaign || '';
    document.getElementById('new-ops').value = item.ops_name || '';
    document.getElementById('new-sales').value = item.sales_contact || '';
    document.getElementById('new-status').value = item.status || 'Yet to start';
    
    // Hide billing type for edits
    document.getElementById('new-billing-type').closest('.filter-group').style.display = 'none';
    
    document.getElementById('new-ro').value = item.ro_amount || 0;
    document.getElementById('new-currency').value = item.currency || 'INR';
    document.getElementById('new-exchange').value = item.exchange_rate || 1;
    document.getElementById('new-start').value = item.start_dt || '';
    document.getElementById('new-end').value = item.end_dt || '';
    
    // New fields
    if(document.getElementById('new-ro-date')) document.getElementById('new-ro-date').value = item.ro_date || '';
    if(document.getElementById('new-ro-number')) document.getElementById('new-ro-number').value = item.ro_number || '';
    if(document.getElementById('new-series')) document.getElementById('new-series').value = item.series || '';
    if(document.getElementById('new-order-id')) document.getElementById('new-order-id').value = item.order_id || '';
    if(document.getElementById('new-inv-date')) document.getElementById('new-inv-date').value = item.inv_date || '';
    if(document.getElementById('new-inv-number')) document.getElementById('new-inv-number').value = item.inv_number || '';
    if(document.getElementById('new-comment')) document.getElementById('new-comment').value = item.comment || '';
    if(document.getElementById('new-platform')) document.getElementById('new-platform').value = item.platform || '';
    if(document.getElementById('new-country')) document.getElementById('new-country').value = item.country || '';

    document.getElementById('add-modal').classList.add('active');
}

function handleAddFormSubmit(e) {
    e.preventDefault();
    const editId = document.getElementById('edit-id').value;
    
    const region = document.getElementById('new-region').value;
    const client = document.getElementById('new-client').value;
    const campaign = document.getElementById('new-campaign').value;
    const ops = document.getElementById('new-ops').value;
    const sales = document.getElementById('new-sales').value;
    const status = document.getElementById('new-status').value;
    const billType = document.getElementById('new-billing-type').value;
    const rawRo = parseFloat(document.getElementById('new-ro').value) || 0;
    const currency = document.getElementById('new-currency').value;
    const exchange = parseFloat(document.getElementById('new-exchange').value) || 1;
    const startDt = document.getElementById('new-start').value;
    const endDt = document.getElementById('new-end').value;

    const roDate = document.getElementById('new-ro-date') ? document.getElementById('new-ro-date').value : '';
    const roNum = document.getElementById('new-ro-number') ? document.getElementById('new-ro-number').value : '';
    const series = document.getElementById('new-series') ? document.getElementById('new-series').value : '';
    const orderId = document.getElementById('new-order-id') ? document.getElementById('new-order-id').value : '';
    const invDate = document.getElementById('new-inv-date') ? document.getElementById('new-inv-date').value : '';
    const invNum = document.getElementById('new-inv-number') ? document.getElementById('new-inv-number').value : '';
    const comment = document.getElementById('new-comment') ? document.getElementById('new-comment').value : '';
    const platform = document.getElementById('new-platform') ? document.getElementById('new-platform').value : '';
    const country = document.getElementById('new-country') ? document.getElementById('new-country').value : '';

    const roInr = rawRo * exchange;

    if (editId) {
        // Edit Mode
        const item = globalData.find(d => d._id === editId);
        if(item) {
            item.region = region;
            item.client_name = client;
            item.campaign = campaign;
            item.ops_name = ops;
            item.sales_contact = sales;
            item.status = status;
            item.ro_amount = roInr;
            // Since we're editing a single row, let's allow them to update the amount (but amount isn't editable here, wait... billing amount = roInr in this form)
            // Let's assume editing updates the amount to roInr. But wait, if it was split, the amount is monthlyRo.
            // Actually, let's keep item.amount unchanged UNLESS they edit ro_amount and it's not a split?
            // To be safe, if we are editing, let's just let amount = roInr because we don't have an "amount" field in the form.
            // The safest is: if they are editing a split item, modifying RO modifies the amount. Let's just set amount = roInr.
            item.amount = roInr; 
            item.currency = currency;
            item.exchange_rate = exchange;
            item.start_dt = startDt;
            item.end_dt = endDt;
            
            item.ro_date = roDate;
            item.ro_number = roNum;
            item.series = series;
            item.order_id = orderId;
            item.inv_date = invDate;
            item.inv_number = invNum;
            item.comment = comment;
            item.platform = platform;
            item.country = country;
            
            // Save to local storage
            let edits = JSON.parse(localStorage.getItem('editedBillingItems') || '{}');
            edits[editId] = { ...item };
            localStorage.setItem('editedBillingItems', JSON.stringify(edits));
        }
    } else {
        // Create Mode
        let newItems = [];
        if (billType === 'Monthly' && startDt && endDt) {
            const sDate = new Date(startDt);
            const eDate = new Date(endDt);
            
            let months = (eDate.getFullYear() - sDate.getFullYear()) * 12;
            months -= sDate.getMonth();
            months += eDate.getMonth();
            months = months <= 0 ? 1 : months + 1;

            const monthlyRo = roInr / months;

            for (let i = 0; i < months; i++) {
                let splitDate = new Date(sDate.getFullYear(), sDate.getMonth() + i, 1);
                let dateStr = splitDate.toISOString().split('T')[0];
                
                newItems.push({
                    _id: 'custom-' + Date.now() + '-' + i,
                    region, date: dateStr, client_name: client, campaign, ops_name: ops,
                    status, ro_amount: roInr, amount: monthlyRo, start_dt: startDt, end_dt: endDt,
                    sales_contact: sales, platform, currency, exchange_rate: exchange,
                    ro_date: roDate, ro_number: roNum, series, order_id: orderId, inv_date: invDate, inv_number: invNum, comment, country
                });
            }
        } else {
            newItems.push({
                _id: 'custom-' + Date.now(),
                region, date: endDt || startDt, client_name: client, campaign, ops_name: ops,
                status, ro_amount: roInr, amount: roInr, start_dt: startDt, end_dt: endDt,
                sales_contact: sales, platform, currency, exchange_rate: exchange,
                ro_date: roDate, ro_number: roNum, series, order_id: orderId, inv_date: invDate, inv_number: invNum, comment, country
            });
        }

        const localItems = JSON.parse(localStorage.getItem('customBillingItems') || '[]');
        localItems.push(...newItems);
        localStorage.setItem('customBillingItems', JSON.stringify(localItems));
        globalData.push(...newItems);
    }
    
    document.getElementById('add-form').reset();
    document.getElementById('add-modal').classList.remove('active');
    
    populateFilters();
    applyFilters();
    renderDashboard();
}

function applyFilters() {
    const regTarget = document.getElementById('region-filter').value;
    const clientTarget = document.getElementById('client-filter').value;
    const opsTarget = document.getElementById('ops-filter').value;
    const salesTarget = document.getElementById('sales-filter').value;
    const timeTarget = document.getElementById('time-filter').value;
    const searchTarget = document.getElementById('search-filter').value.toLowerCase().trim();
    
    const dFrom = new Date(document.getElementById('date-from').value);
    const dTo = new Date(document.getElementById('date-to').value);
    
    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    filteredData = globalData.filter(d => {
        let textMatch = (regTarget === 'All' || d.region === regTarget) &&
               (clientTarget === 'All' || d.client_name === clientTarget) &&
               (opsTarget === 'All' || d.ops_name === opsTarget) &&
               (salesTarget === 'All' || d.sales_contact === salesTarget);
               
        if (!textMatch) return false;
        
        if (searchTarget !== "") {
            const cl = d.client_name ? d.client_name.toLowerCase() : "";
            const cam = d.campaign ? d.campaign.toLowerCase() : "";
            const op = d.ops_name ? d.ops_name.toLowerCase() : "";
            const sa = d.sales_contact ? d.sales_contact.toLowerCase() : "";
            if (!cl.includes(searchTarget) && !cam.includes(searchTarget) && !op.includes(searchTarget) && !sa.includes(searchTarget)) {
                return false;
            }
        }

        if (timeTarget === 'All') return true;
        
        if (!d.date || d.date === 'Unknown' || d.date === '') return false;
        
        const itemDate = new Date(d.date);
        if (isNaN(itemDate.getTime())) return false;
        
        if (timeTarget === 'This Month') {
            return itemDate.getMonth() === currentMonth && itemDate.getFullYear() === currentYear;
        } else if (timeTarget === 'Last Month') {
            let lm = currentMonth - 1;
            let ly = currentYear;
            if (lm < 0) { lm = 11; ly--; }
            return itemDate.getMonth() === lm && itemDate.getFullYear() === ly;
        } else if (timeTarget === 'Custom') {
            if (!isNaN(dFrom.getTime()) && itemDate < dFrom) return false;
            if (!isNaN(dTo.getTime())) {
                const toEnd = new Date(dTo.getTime());
                toEnd.setHours(23, 59, 59, 999);
                if (itemDate > toEnd) return false;
            }
        }
        return true;
    });

    renderDashboard();
}

function getStatusBadge(statusStr) {
    if(!statusStr) return '-';
    let s = statusStr.toLowerCase();
    if(s.includes('yet to start')) return `<span class="badge badge-grey">${statusStr}</span>`;
    if(s.includes('delivering')) return `<span class="badge badge-green">${statusStr}</span>`;
    if(s.includes('stop') || s.includes('complet') || s.includes('paus')) return `<span class="badge badge-red">${statusStr}</span>`;
    if(s.includes('invoice')) return `<span class="badge badge-blue">${statusStr}</span>`;
    return `<span class="badge badge-grey">${statusStr}</span>`;
}

function renderDashboard() {
    const totalRev = filteredData.reduce((sum, d) => sum + (d.amount || 0), 0);
    const totalCamp = new Set(filteredData.map(d => d.campaign)).size;
    
    document.getElementById('kpi-revenue').textContent = `₹${(totalRev / 100000).toLocaleString('en-IN', { maximumFractionDigits: 2 })} L`;
    document.getElementById('kpi-campaigns').textContent = totalCamp.toLocaleString('en-IN');
    document.getElementById('kpi-records').textContent = filteredData.length.toLocaleString('en-IN');

    updateTrendChart();
    updateClientChart();
    updateRegionChart();
    renderSummaryTable();
    renderTables();
}

function renderSummaryTable() {
    const tableBody = document.querySelector('#table-summary tbody');
    if (!tableBody) return;
    let summaryData = {};
    let grandTotal = 0;
    
    filteredData.forEach(d => {
        const r = d.region || "Unknown";
        if (!summaryData[r]) {
            summaryData[r] = { records: 0, campaigns: new Set(), revenue: 0 };
        }
        summaryData[r].records += 1;
        if(d.campaign) summaryData[r].campaigns.add(d.campaign);
        summaryData[r].revenue += (d.amount || 0);
        grandTotal += (d.amount || 0);
    });

    let html = [];
    for (const [region, data] of Object.entries(summaryData)) {
        html.push(`<tr>
            <td>${region}</td>
            <td>${data.records.toLocaleString('en-IN')}</td>
            <td>${data.campaigns.size.toLocaleString('en-IN')}</td>
            <td>₹${(data.revenue / 100000).toLocaleString('en-IN', {maximumFractionDigits: 2})} L</td>
        </tr>`);
    }

    tableBody.innerHTML = html.join('');
    document.getElementById('summary-table-footer-total').textContent = `₹${(grandTotal / 100000).toLocaleString('en-IN', {maximumFractionDigits: 2})} L`;
}

function renderTables() {
    const tableIndia = document.querySelector('#table-india tbody');
    const tableExport = document.querySelector('#table-export tbody');
    const tablePg = document.querySelector('#table-pg tbody');
    
    let indHtml = [];
    let expHtml = [];
    let pgHtml = [];
    
    let indTotal = 0;
    let expTotal = 0;
    let pgTotal = 0;
    
    const maxRows = 1000;
    
    filteredData.forEach(d => {
        // Date | Client Name | Campaign | Ops | Sales | Status | RO Date | RO# | Series | Order ID | Inv Date | Inv# | Comment | Platform | Country | RO Amt | Revenue (₹)
        const row = `<tr>
            <td>${d.date || '-'}</td>
            <td>${d.client_name || '-'}</td>
            <td>${d.campaign || '-'}</td>
            <td>${d.ops_name || '-'}</td>
            <td>${d.sales_contact || '-'}</td>
            <td>${getStatusBadge(d.status)}</td>
            <td>${d.ro_date || '-'}</td>
            <td>${d.ro_number || '-'}</td>
            <td>${d.series || '-'}</td>
            <td>${d.order_id || '-'}</td>
            <td>${d.inv_date || '-'}</td>
            <td>${d.inv_number || '-'}</td>
            <td>${d.comment || '-'}</td>
            <td>${d.platform || '-'}</td>
            <td>${d.country || '-'}</td>
            <td>₹${(d.ro_amount || 0).toLocaleString('en-IN', {maximumFractionDigits: 2})}</td>
            <td>₹${(d.amount || 0).toLocaleString('en-IN', {maximumFractionDigits: 2})}</td>
            <td>
                <div style="display: flex; gap: 0.5rem;">
                    <button class="edit-btn" data-id="${d._id}" style="padding: 4px 8px; font-size: 0.9em; background: rgba(88, 166, 255, 0.2); border: none; border-radius: 4px; color: #58a6ff; cursor: pointer;">✎ Edit</button>
                    <button class="generate-btn" data-id="${d._id}" style="padding: 4px 8px; font-size: 0.9em; background: rgba(46, 160, 67, 0.2); border: none; border-radius: 4px; color: #3fb950; cursor: pointer;">📄 DOCX</button>
                    <button class="pdf-btn" data-id="${d._id}" style="padding: 4px 8px; font-size: 0.9em; background: rgba(210, 43, 43, 0.2); border: none; border-radius: 4px; color: #ff5e5e; cursor: pointer;">📄 PDF</button>
                </div>
            </td>
        </tr>`;
        
        if (d.region === "India") {
            indTotal += (d.amount || 0);
            if (indHtml.length < maxRows) indHtml.push(row);
        } else if (d.region === "Foreign") {
            expTotal += (d.amount || 0);
            if (expHtml.length < maxRows) expHtml.push(row);
        } else if (d.region.includes("PG")) {
            pgTotal += (d.amount || 0);
            if (pgHtml.length < maxRows) pgHtml.push(row);
        }
    });

    if(tableIndia) tableIndia.innerHTML = indHtml.join('');
    if(tableExport) tableExport.innerHTML = expHtml.join('');
    if(tablePg) tablePg.innerHTML = pgHtml.join('');

    // Attach edit and generate listeners
    document.querySelectorAll('.edit-btn').forEach(btn => {
        btn.addEventListener('click', handleEditClick);
    });
    document.querySelectorAll('.generate-btn').forEach(btn => {
        btn.addEventListener('click', handleGenerateClick);
    });
    document.querySelectorAll('.pdf-btn').forEach(btn => {
        btn.addEventListener('click', handlePdfGenerateClick);
    });

    const fInd = `₹${(indTotal / 100000).toLocaleString('en-IN', {maximumFractionDigits: 2})} L`;
    const fExp = `₹${(expTotal / 100000).toLocaleString('en-IN', {maximumFractionDigits: 2})} L`;
    const fPg = `₹${(pgTotal / 100000).toLocaleString('en-IN', {maximumFractionDigits: 2})} L`;

    if(document.getElementById('india-total-inr')) document.getElementById('india-total-inr').textContent = `Total: ${fInd}`;
    if(document.getElementById('export-total-inr')) document.getElementById('export-total-inr').textContent = `Total: ${fExp}`;
    if(document.getElementById('pg-total-inr')) document.getElementById('pg-total-inr').textContent = `Total: ${fPg}`;

    if(document.getElementById('india-table-footer-total')) document.getElementById('india-table-footer-total').textContent = fInd;
    if(document.getElementById('export-table-footer-total')) document.getElementById('export-table-footer-total').textContent = fExp;
    if(document.getElementById('pg-table-footer-total')) document.getElementById('pg-table-footer-total').textContent = fPg;
}

function createChart(ctxId, type, data, options) {
    const el = document.getElementById(ctxId);
    if(!el) return;
    const ctx = el.getContext('2d');
    if (charts[ctxId]) {
        charts[ctxId].destroy();
    }
    charts[ctxId] = new Chart(ctx, { type, data, options });
}

function updateTrendChart() {
    const grouped = {};
    filteredData.forEach(d => {
        if(!d.date || d.date === 'Unknown' || d.date === '') return;
        const dObj = new Date(d.date);
        if(isNaN(dObj.getTime())) return;
        const key = `${dObj.getFullYear()}-${String(dObj.getMonth()+1).padStart(2, '0')}`;
        grouped[key] = (grouped[key] || 0) + d.amount;
    });

    const sorted = Object.keys(grouped).sort();
    const dataVals = sorted.map(k => grouped[k] / 100000); // Lakhs

    const data = {
        labels: sorted,
        datasets: [{
            label: 'Revenue (₹ Lakhs)',
            data: dataVals,
            borderColor: '#58a6ff',
            backgroundColor: 'rgba(88, 166, 255, 0.2)',
            borderWidth: 3,
            fill: true,
            tension: 0.4,
            pointBackgroundColor: '#fff',
            pointRadius: 5
        }]
    };
    
    const options = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: { display: false }
        }
    };
    createChart('trendChart', 'line', data, options);
}

function updateClientChart() {
    const grouped = {};
    filteredData.forEach(d => {
        if (!d.client_name || d.client_name === "Unknown") return;
        grouped[d.client_name] = (grouped[d.client_name] || 0) + d.amount;
    });

    const sorted = Object.entries(grouped)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 10);
        
    const data = {
        labels: sorted.map(s => s[0].length > 15 ? s[0].slice(0, 15) + '...' : s[0]),
        datasets: [{
            label: 'Revenue',
            data: sorted.map(s => s[1] / 100000), // Lakhs
            backgroundColor: 'rgba(132, 60, 250, 0.8)',
            borderRadius: 6
        }]
    };

    const options = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: { display: false }
        }
    };
    createChart('agencyChart', 'bar', data, options); // using existing canvas ID
}

function updateRegionChart() {
    const grouped = {};
    filteredData.forEach(d => {
        const r = d.region || "Unknown";
        grouped[r] = (grouped[r] || 0) + d.amount;
    });

    const data = {
        labels: Object.keys(grouped),
        datasets: [{
            data: Object.values(grouped).map(v => v / 100000),
            backgroundColor: ['#353ae6', '#843cfa', '#fa3cc3', '#2ea043', '#58a6ff', '#f85149'],
            borderWidth: 0,
            hoverOffset: 12
        }]
    };

    const options = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                position: 'right',
                labels: { color: '#e6edf3', padding: 20 }
            }
        },
        cutout: '75%'
    };
    createChart('regionChart', 'doughnut', data, options);
}

init();
